# ============================================================
# MedGraph Free - Template Definitions (410+ templates)
# ============================================================

TEMPLATES <- list(

# ================================================================
# BIOCHEMISTRY (30)
# ================================================================
D("michaelis-menten","biochem","Michaelis-Menten Plot","ミカエリス・メンテンプロット",
  "[S] (substrate concentration, mM)","v (reaction velocity, umol/min)",c(0,10),c(0,10),
  "酵素反応速度論の基本グラフ。基質濃度[S]と反応速度vの双曲線関係をプロットするテンプレート。","酵素,Km,Vmax,反応速度,動力学",
  hl=list(c(9,"Vmax"))),
D("lineweaver-burk","biochem","Lineweaver-Burk Plot","ラインウィーバー・バークプロット",
  "1/[S] (mM^-1)","1/v (umol/min)^-1",c(-3,10),c(-3,10),
  "二重逆数プロット。Michaelis-Menten式を線形化してKmとVmaxを求めるためのテンプレート。","二重逆数,Km,Vmax,線形化"),
D("titration","biochem","pH Titration Curve","pH滴定曲線",
  "Volume of titrant (mL)","pH",c(0,50),c(0,14),
  "酸塩基滴定のpH変化を記録するテンプレート。当量点や緩衝域の解析に使用。","pH,滴定,当量点,緩衝",
  hl=list(c(7,"pH 7","grey70"))),
D("competitive-inhibition","biochem","Competitive Inhibition","拮抗阻害",
  "[S] (mM)","v (umol/min)",c(0,10),c(0,10),
  "拮抗阻害の酵素反応速度。Km変化・Vmax不変をプロットするテンプレート。","酵素阻害,拮抗,Km,Vmax",
  sub="Plot: No inhibitor / + Competitive inhibitor"),
D("uncompetitive-inhibition","biochem","Uncompetitive Inhibition","不拮抗阻害",
  "[S] (mM)","v (umol/min)",c(0,10),c(0,10),
  "不拮抗阻害の酵素反応速度。Km・Vmax共に変化するパターンをプロットするテンプレート。","酵素阻害,不拮抗,動力学",
  sub="Plot: No inhibitor / + Uncompetitive inhibitor"),
D("noncompetitive-inhibition","biochem","Noncompetitive Inhibition","非拮抗阻害",
  "[S] (mM)","v (umol/min)",c(0,10),c(0,10),
  "非拮抗阻害の酵素反応速度。Km不変・Vmax低下をプロットするテンプレート。","酵素阻害,非拮抗,動力学",
  sub="Plot: No inhibitor / + Noncompetitive inhibitor"),
D("mixed-inhibition","biochem","Mixed Inhibition","混合阻害",
  "[S] (mM)","v (umol/min)",c(0,10),c(0,10),
  "混合阻害の酵素反応速度。KmとVmaxの両方が変化するパターンのテンプレート。","酵素阻害,混合型,動力学",
  sub="Plot: No inhibitor / + Mixed inhibitor"),
D("eadie-hofstee","biochem","Eadie-Hofstee Plot","イーディ・ホフステープロット",
  "v/[S] (min^-1)","v (umol/min)",c(0,5),c(0,10),
  "Eadie-Hofsteeプロット。v対v/[S]のプロットでVmaxとKmを決定するテンプレート。","Eadie-Hofstee,酵素,線形化"),
D("hanes-woolf","biochem","Hanes-Woolf Plot","ヘインズ・ウルフプロット",
  "[S] (mM)","[S]/v (min)",c(-2,10),c(-2,10),
  "Hanes-Woolfプロット。[S]/v対[S]の線形プロットでKmとVmaxを求めるテンプレート。","Hanes-Woolf,酵素,線形化"),
D("hill-plot","biochem","Hill Plot","ヒルプロット",
  "log [S]","log(Y/(1-Y))",c(-2,2),c(-3,3),
  "ヒルプロット。協同結合の度合い（Hill係数n）を求めるためのテンプレート。","Hill係数,協同性,結合"),
D("scatchard","biochem","Scatchard Plot","スキャッチャードプロット",
  "Bound","Bound/Free",c(0,10),c(0,5),
  "スキャッチャードプロット。受容体結合解析でKdとBmaxを求めるテンプレート。","Scatchard,結合,Kd,Bmax"),
D("protein-denaturation","biochem","Protein Denaturation Curve","タンパク質変性曲線",
  "Temperature (C)","Fraction folded",c(20,90),c(0,1),
  "タンパク質の熱変性曲線。温度上昇に伴う折り畳み構造の喪失をプロットするテンプレート。","変性,Tm,熱安定性",
  hl=list(c(0.5,"Tm (50% unfolded)"))),
D("beer-lambert","biochem","Beer-Lambert Plot","ベール・ランベルトプロット",
  "Concentration (M)","Absorbance (A)",c(0,0.1),c(0,2),
  "ベール・ランベルトの法則の検量線。濃度と吸光度の線形関係をプロットするテンプレート。","吸光度,検量線,分光"),
D("bradford-assay","biochem","Bradford Assay Standard Curve","ブラッドフォード検量線",
  "Protein concentration (ug/mL)","Absorbance (595 nm)",c(0,2000),c(0,1.5),
  "ブラッドフォードアッセイの検量線。タンパク質定量に使用するテンプレート。","ブラッドフォード,タンパク質定量,検量線"),
D("spectrophotometry","biochem","Spectrophotometry Standard","分光光度法検量線",
  "Concentration","Absorbance",c(0,10),c(0,2),
  "分光光度法の標準検量線テンプレート。任意の物質の濃度-吸光度関係をプロット。","分光,検量線,吸光度"),
D("substrate-saturation","biochem","Substrate Saturation Curve","基質飽和曲線",
  "[S] (mM)","v (umol/min)",c(0,20),c(0,10),
  "基質飽和曲線。高基質濃度域でのVmaxへの収束をプロットするテンプレート。","基質飽和,酵素,Vmax"),
D("allosteric-enzyme","biochem","Allosteric Enzyme (Sigmoidal)","アロステリック酵素（S字型）",
  "[S] (mM)","v (umol/min)",c(0,10),c(0,10),
  "アロステリック酵素のS字型（シグモイド）速度曲線テンプレート。協同性の解析に使用。","アロステリック,協同性,シグモイド"),
D("reaction-coordinate","biochem","Reaction Coordinate Diagram","反応座標図",
  "Reaction coordinate","Free energy (G)",c(0,10),c(0,10),
  "反応座標図。活性化エネルギーや遷移状態のエネルギープロファイルを描くテンプレート。","活性化エネルギー,遷移状態,反応座標",
  ann=list(c(3,8,"Transition state","grey55",3),c(1,4,"Reactants","grey55",3),c(8,3,"Products","grey55",3))),
D("arrhenius","biochem","Arrhenius Plot","アレニウスプロット",
  "1/T (K^-1) x 1000","ln(k)",c(2.8,3.6),c(-5,5),
  "アレニウスプロット。温度と反応速度定数の関係から活性化エネルギーを求めるテンプレート。","アレニウス,活性化エネルギー,温度"),
D("buffer-capacity","biochem","Buffer Capacity Curve","緩衝能曲線",
  "pH","Buffer capacity (beta)",c(0,14),c(0,0.1),
  "緩衝能曲線。pHに対する緩衝能の変化をプロットするテンプレート。","緩衝液,緩衝能,pH"),
D("chromatography","biochem","Chromatography Elution","クロマトグラフィー溶出プロファイル",
  "Elution volume (mL)","Absorbance (280 nm)",c(0,100),c(0,2),
  "カラムクロマトグラフィーの溶出プロファイルテンプレート。ピーク分離の解析に使用。","クロマトグラフィー,溶出,カラム"),
D("enzyme-ph","biochem","Enzyme Activity vs pH","酵素活性-pH曲線",
  "pH","Relative activity (%)",c(0,14),c(0,100),
  "酵素活性とpHの関係を示す曲線テンプレート。至適pHの決定に使用。","酵素活性,至適pH"),
D("enzyme-temp","biochem","Enzyme Activity vs Temperature","酵素活性-温度曲線",
  "Temperature (C)","Relative activity (%)",c(0,80),c(0,100),
  "酵素活性と温度の関係を示す曲線テンプレート。至適温度の決定に使用。","酵素活性,至適温度"),
D("dna-melting","biochem","DNA Melting Curve","DNA融解曲線",
  "Temperature (C)","Absorbance (260 nm)",c(40,100),c(0.5,1.5),
  "DNA融解曲線（Tm測定）。温度上昇に伴う吸光度変化をプロットするテンプレート。","DNA,融解,Tm,吸光度"),
D("amino-acid-titration","biochem","Amino Acid Titration","アミノ酸滴定曲線",
  "Equivalents of OH-","pH",c(0,3),c(0,14),
  "アミノ酸の滴定曲線テンプレート。pKa値とpIの決定に使用。","アミノ酸,pKa,pI,滴定"),
D("sds-page","biochem","SDS-PAGE Molecular Weight","SDS-PAGE分子量推定",
  "Rf (relative migration)","log MW (kDa)",c(0,1),c(1,2.5),
  "SDS-PAGE分子量推定の検量線テンプレート。Rf値と分子量の対数関係をプロット。","SDS-PAGE,分子量,電気泳動"),
D("western-blot-quant","biochem","Western Blot Quantification","ウエスタンブロット定量",
  "Protein amount (ug)","Band intensity (AU)",c(0,50),c(0,100),
  "ウエスタンブロットのバンド強度定量テンプレート。タンパク質量との関係をプロット。","ウエスタンブロット,定量,バンド強度"),
D("henderson-hasselbalch","biochem","Henderson-Hasselbalch Curve","ヘンダーソン・ハッセルバルヒ曲線",
  "[A-]/[HA] ratio","pH",c(0,10),c(0,14),
  "ヘンダーソン・ハッセルバルヒ式に基づくpH計算テンプレート。","pH,緩衝,pKa"),
D("protein-standard","biochem","BCA Protein Standard Curve","BCA検量線",
  "BSA concentration (ug/mL)","Absorbance (562 nm)",c(0,2000),c(0,2),
  "BCAアッセイの検量線テンプレート。タンパク質定量に使用。","BCA,タンパク質定量,検量線"),
D("km-vmax-comparison","biochem","Km/Vmax Comparison","Km/Vmax比較プロット",
  "[S] (mM)","v (umol/min)",c(0,10),c(0,10),
  "複数酵素のKm/Vmax比較テンプレート。異なる酵素の速度論パラメータを比較。","Km,Vmax,比較,酵素",
  sub="Plot curves for multiple enzymes"),

# ================================================================
# PHYSIOLOGY (35)
# ================================================================
D("o2-dissociation","physiol","O2 Dissociation Curve","酸素解離曲線",
  "PO2 (mmHg)","O2 saturation (%)",c(0,100),c(0,100),
  "ヘモグロビンの酸素解離曲線テンプレート。PO2とSaO2のS字型関係をプロット。","酸素解離,ヘモグロビン,S字型,SaO2",
  hl=list(c(50,"P50"))),
D("o2-dissociation-bohr","physiol","O2 Dissociation (Bohr Effect)","酸素解離曲線（ボーア効果）",
  "PO2 (mmHg)","O2 saturation (%)",c(0,100),c(0,100),
  "ボーア効果による酸素解離曲線のシフトを示すテンプレート。pH変化の影響を比較。","ボーア効果,pH,酸素解離",
  sub="Plot: Normal / Low pH / High pH"),
D("co2-dissociation","physiol","CO2 Dissociation Curve","CO2解離曲線",
  "PCO2 (mmHg)","CO2 content (mL/dL)",c(0,80),c(0,70),
  "CO2解離曲線テンプレート。PCO2とCO2含量の関係をプロット。","CO2,解離,ホルデン効果"),
D("frank-starling","physiol","Frank-Starling Curve","フランク・スターリング曲線",
  "End-diastolic volume (mL)","Stroke volume (mL)",c(0,200),c(0,150),
  "フランク・スターリング曲線テンプレート。前負荷と一回拍出量の関係をプロット。","フランク・スターリング,前負荷,心拍出量"),
D("nerve-ap","physiol","Nerve Action Potential","神経活動電位",
  "Time (ms)","Membrane potential (mV)",c(0,5),c(-90,50),
  "神経細胞の活動電位テンプレート。脱分極・再分極・過分極のパターンをプロット。","活動電位,脱分極,再分極,神経",
  hl=list(c(-70,"Resting potential","grey60"),c(-55,"Threshold","#E74C3C"))),
D("cardiac-ap","physiol","Cardiac Action Potential","心筋活動電位",
  "Time (ms)","Membrane potential (mV)",c(0,400),c(-90,40),
  "心室筋の活動電位テンプレート。Phase 0-4の各段階をプロット。","心筋,活動電位,Phase,プラトー",
  ann=list(c(20,30,"Phase 0","grey55",3),c(80,10,"Phase 1","grey55",3),c(150,5,"Phase 2","grey55",3),c(280,-40,"Phase 3","grey55",3),c(380,-80,"Phase 4","grey55",3))),
D("sa-node-ap","physiol","SA Node Action Potential","洞房結節活動電位",
  "Time (ms)","Membrane potential (mV)",c(0,500),c(-70,20),
  "洞房結節のペースメーカー活動電位テンプレート。自動能をプロット。","洞房結節,ペースメーカー,自動能"),
D("flow-volume","physiol","Flow-Volume Loop","フローボリュームループ",
  "Volume (L)","Flow (L/s)",c(0,6),c(-8,12),
  "フローボリュームループテンプレート。呼気・吸気の流量と容量の関係をプロット。","フローボリューム,呼吸機能,肺",
  hl=list(c(0,"","grey80"))),
D("pv-loop","physiol","Cardiac PV Loop","心臓PVループ",
  "Volume (mL)","Pressure (mmHg)",c(0,150),c(0,150),
  "心臓の圧-容量ループテンプレート。左室の一心周期の変化をプロット。","PVループ,圧容量,心周期"),
D("wiggers","physiol","Wiggers Diagram","ウィガースダイアグラム",
  "Time (ms)","Pressure (mmHg) / Volume (mL)",c(0,800),c(0,130),
  "ウィガースダイアグラムテンプレート。心周期の圧・容量・ECG・心音の時間経過。","ウィガース,心周期,大動脈圧,心室圧"),
D("lung-compliance","physiol","Lung Compliance Curve","肺コンプライアンス曲線",
  "Transpulmonary pressure (cmH2O)","Volume (L)",c(0,30),c(0,6),
  "肺コンプライアンス曲線テンプレート。圧-容量関係をプロット。","コンプライアンス,肺,圧-容量"),
D("muscle-twitch","physiol","Muscle Twitch","筋単収縮",
  "Time (ms)","Force (% max)",c(0,200),c(0,100),
  "骨格筋の単収縮テンプレート。潜時・収縮期・弛緩期をプロット。","単収縮,骨格筋,収縮"),
D("length-tension","physiol","Length-Tension Relationship","筋長-張力関係",
  "Sarcomere length (um)","Tension (% max)",c(1,4),c(0,100),
  "筋のサルコメア長と張力の関係テンプレート。至適長の決定に使用。","サルコメア,張力,至適長"),
D("force-velocity","physiol","Force-Velocity Relationship","筋力-速度関係",
  "Load (% max)","Velocity of shortening",c(0,100),c(0,10),
  "筋力-速度関係テンプレート。負荷と短縮速度の双曲線関係をプロット。","筋力,速度,負荷"),
D("spirometry","physiol","Spirometry Tracing","スパイロメトリー",
  "Time (s)","Volume (L)",c(0,10),c(0,6),
  "スパイロメトリーのトレーシングテンプレート。FVC・FEV1の測定に使用。","スパイロメトリー,FVC,FEV1,肺機能"),
D("lung-volumes","physiol","Lung Volumes Diagram","肺容量区分図",
  "Time","Volume (L)",c(0,10),c(0,7),
  "肺気量区分図テンプレート。TV・IRV・ERV・RV・TLC等をプロット。","肺容量,TV,IRV,ERV,RV,TLC"),
D("vq-ratio","physiol","V/Q Ratio","換気血流比",
  "V/Q ratio","Relative amount",c(0,3),c(0,10),
  "換気血流比のテンプレート。肺の上部から下部までのV/Q分布をプロット。","換気血流比,V/Q,ガス交換"),
D("starling-forces","physiol","Starling Forces","スターリングの力",
  "Position along capillary","Pressure (mmHg)",c(0,10),c(0,40),
  "毛細血管のスターリングの力テンプレート。静水圧と膠質浸透圧の関係をプロット。","スターリング,毛細血管,浸透圧",
  ann=list(c(2,35,"Arteriolar end","grey55",3),c(8,35,"Venular end","grey55",3))),
D("venous-return","physiol","Venous Return Curve","静脈還流曲線",
  "Right atrial pressure (mmHg)","Venous return (L/min)",c(-2,10),c(0,10),
  "静脈還流曲線テンプレート。右房圧と静脈還流量の関係をプロット。","静脈還流,右房圧,心拍出量"),
D("cardiac-function","physiol","Cardiac Function Curve","心機能曲線",
  "Right atrial pressure (mmHg)","Cardiac output (L/min)",c(-2,10),c(0,10),
  "心機能曲線テンプレート。右房圧と心拍出量の関係をプロット。","心機能,心拍出量,フランク・スターリング"),
D("guyton","physiol","Guyton Diagram","ガイトン図",
  "Right atrial pressure (mmHg)","Flow (L/min)",c(-2,10),c(0,10),
  "ガイトン図テンプレート。心機能曲線と静脈還流曲線の交点で心拍出量を決定。","ガイトン,心拍出量,静脈還流",
  sub="Cardiac function + Venous return intersection"),
D("respiratory-pv","physiol","Respiratory PV Curve","呼吸系圧-容量曲線",
  "Pressure (cmH2O)","Volume (L)",c(-20,40),c(0,6),
  "呼吸系全体の圧-容量曲線テンプレート。肺と胸壁の合計コンプライアンスをプロット。","呼吸系,圧-容量,コンプライアンス"),
D("fetal-hb","physiol","Fetal Hb Dissociation","胎児ヘモグロビン解離曲線",
  "PO2 (mmHg)","O2 saturation (%)",c(0,100),c(0,100),
  "胎児ヘモグロビン（HbF）と成人ヘモグロビン（HbA）の酸素解離曲線比較テンプレート。","HbF,HbA,胎児,酸素解離",
  sub="Plot: HbA / HbF comparison"),
D("compliance-comparison","physiol","Compliance Comparison","コンプライアンス比較",
  "Pressure (cmH2O)","Volume (L)",c(-20,40),c(0,6),
  "肺・胸壁・呼吸系全体のコンプライアンス比較テンプレート。","コンプライアンス,肺,胸壁,比較",
  sub="Lung / Chest wall / Total"),
D("capnography","physiol","Capnography Waveform","カプノグラフィー波形",
  "Time (s)","EtCO2 (mmHg)",c(0,10),c(0,50),
  "カプノグラフィー波形テンプレート。呼気終末CO2濃度の経時変化をモニタリング。","カプノグラフィー,EtCO2,モニタリング"),
D("baroreceptor","physiol","Baroreceptor Response","圧受容器反射",
  "Mean arterial pressure (mmHg)","Nerve firing rate (Hz)",c(40,180),c(0,100),
  "動脈圧受容器の応答曲線テンプレート。血圧と神経発火頻度の関係をプロット。","圧受容器,血圧,反射"),
D("renal-autoregulation","physiol","Renal Autoregulation","腎自動調節",
  "Renal perfusion pressure (mmHg)","Renal blood flow (mL/min)",c(0,200),c(0,700),
  "腎自動調節曲線テンプレート。灌流圧と腎血流の関係をプロット。","腎自動調節,腎血流,灌流圧",
  zones=list(c(80,180,400,600,"green",0.08)),
  ann=list(c(130,550,"Autoregulatory range","#27ae60",3))),
D("countercurrent","physiol","Countercurrent Multiplier","対向流増幅系",
  "Position (cortex to medulla)","Osmolality (mOsm/kg)",c(0,10),c(200,1400),
  "腎臓の対向流増幅系テンプレート。皮質から髄質への浸透圧勾配をプロット。","対向流,浸透圧,尿濃縮"),
D("membrane-potential","physiol","Resting Membrane Potential","静止膜電位",
  "[K+]o (mM)","Membrane potential (mV)",c(1,100),c(-100,0),
  "細胞外カリウム濃度と静止膜電位の関係テンプレート。Nernst式の検証に使用。","膜電位,Nernst,カリウム",xlog=TRUE),
D("cardiac-output-hr","physiol","Cardiac Output vs HR","心拍出量-心拍数曲線",
  "Heart rate (bpm)","Cardiac output (L/min)",c(40,200),c(0,20),
  "心拍数と心拍出量の関係テンプレート。至適心拍数と最大心拍出量をプロット。","心拍出量,心拍数"),
D("body-fluid","physiol","Body Fluid Compartments","体液区分",
  "Compartment","Volume (L)",c(0,5),c(0,45),
  "体液区分テンプレート。ICF・ECF（ISF+Plasma）の容量分布をプロット。","体液,ICF,ECF,ISF",
  xb=c(1,2,3,4), xlb=c("ICF","ISF","Plasma","Total")),
D("graded-potential","physiol","Graded Potential","段階電位",
  "Distance from stimulus (mm)","Amplitude (mV)",c(0,20),c(0,30),
  "段階電位のテンプレート。距離に伴う減衰をプロット。活動電位との比較に使用。","段階電位,シナプス,減衰"),
D("smooth-muscle-ap","physiol","Smooth Muscle Action Potential","平滑筋活動電位",
  "Time (ms)","Membrane potential (mV)",c(0,2000),c(-70,10),
  "平滑筋の活動電位テンプレート。スローウェーブとスパイクのパターンをプロット。","平滑筋,スローウェーブ,活動電位"),
D("tetanus","physiol","Muscle Tetanus","筋強縮",
  "Time (ms)","Force (% max)",c(0,500),c(0,100),
  "骨格筋の強縮テンプレート。不完全強縮と完全強縮のパターンをプロット。","強縮,骨格筋,収縮",
  sub="Unfused tetanus / Fused tetanus"),

# ================================================================
# PHARMACOLOGY (25)
# ================================================================
D("dose-response-graded","pharm","Graded Dose-Response","段階的用量反応曲線",
  "log [Drug] (M)","Response (% max)",c(-9,-3),c(0,100),
  "段階的用量反応曲線テンプレート。EC50の決定に使用。","用量反応,EC50,Emax",
  hl=list(c(50,"EC50"))),
D("dose-response-quantal","pharm","Quantal Dose-Response","量子的用量反応曲線",
  "log Dose (mg/kg)","Cumulative % responding",c(-1,3),c(0,100),
  "量子的用量反応曲線テンプレート。ED50・TD50・LD50の決定に使用。","量子的,ED50,TD50,LD50",
  sub="Plot: Therapeutic / Toxic / Lethal"),
D("pk-iv-bolus","pharm","PK: IV Bolus","薬物動態（静注ボーラス）",
  "Time (hr)","Plasma concentration (ug/mL)",c(0,24),c(0,100),
  "静脈内ボーラス投与後の血中濃度推移テンプレート。一次速度式に基づくモデル。","薬物動態,静注,血中濃度"),
D("pk-oral","pharm","PK: Oral Administration","薬物動態（経口投与）",
  "Time (hr)","Plasma concentration (ug/mL)",c(0,24),c(0,50),
  "経口投与後の血中濃度推移テンプレート。吸収相と消失相をプロット。","薬物動態,経口,Cmax,Tmax",
  ann=list(c(3,45,"Cmax","grey55",3),c(3,42,"Tmax","grey55",3))),
D("pk-multiple-dose","pharm","PK: Multiple Dosing","薬物動態（反復投与）",
  "Time (hr)","Plasma concentration (ug/mL)",c(0,72),c(0,50),
  "反復投与時の血中濃度推移テンプレート。定常状態への到達をプロット。","薬物動態,反復投与,定常状態,蓄積"),
D("pk-semilog","pharm","PK: Semi-log Plot","薬物動態片対数プロット",
  "Time (hr)","Plasma concentration (log scale)",c(0,24),c(0.1,100),
  "薬物動態の片対数プロットテンプレート。半減期の決定に使用。","薬物動態,片対数,半減期",ylog=TRUE),
D("therapeutic-window","pharm","Therapeutic Window","治療域",
  "Time (hr)","Plasma concentration (ug/mL)",c(0,48),c(0,50),
  "治療域テンプレート。MEC（最小有効濃度）とMTC（最小中毒濃度）の範囲をプロット。","治療域,MEC,MTC",
  hl=list(c(10,"MEC","#2E86AB"),c(40,"MTC","#E74C3C")),
  zones=list(c(0,48,10,40,"green",0.06))),
D("schild-plot","pharm","Schild Plot","シルドプロット",
  "log [Antagonist] (M)","log (DR - 1)",c(-9,-4),c(-1,3),
  "シルドプロット。競合的拮抗薬のpA2値を決定するテンプレート。","シルド,pA2,拮抗薬"),
D("isobologram","pharm","Isobologram","アイソボログラム",
  "Drug A dose","Drug B dose",c(0,10),c(0,10),
  "アイソボログラムテンプレート。2薬の相互作用（相乗・相加・拮抗）を評価。","アイソボログラム,相互作用,相乗"),
D("competitive-antagonist","pharm","Competitive Antagonist","競合的拮抗薬",
  "log [Agonist] (M)","Response (% max)",c(-9,-3),c(0,100),
  "競合的拮抗薬存在下の用量反応曲線テンプレート。右方シフトをプロット。","競合的拮抗,右方シフト",
  sub="Plot: Agonist alone / + Antagonist"),
D("noncompetitive-antagonist","pharm","Noncompetitive Antagonist","非競合的拮抗薬",
  "log [Agonist] (M)","Response (% max)",c(-9,-3),c(0,100),
  "非競合的拮抗薬存在下の用量反応曲線テンプレート。Emax低下をプロット。","非競合的拮抗,Emax低下",
  sub="Plot: Agonist alone / + Antagonist"),
D("partial-agonist","pharm","Partial Agonist","部分作動薬",
  "log [Drug] (M)","Response (% max)",c(-9,-3),c(0,100),
  "部分作動薬の用量反応曲線テンプレート。完全作動薬との比較をプロット。","部分作動薬,intrinsic activity",
  sub="Full agonist / Partial agonist"),
D("bioavailability","pharm","Bioavailability Comparison","バイオアベイラビリティ比較",
  "Time (hr)","Plasma concentration (ug/mL)",c(0,24),c(0,50),
  "投与経路別バイオアベイラビリティ比較テンプレート。AUC比からF値を算出。","バイオアベイラビリティ,AUC,F値",
  sub="IV / Oral comparison"),
D("first-pass","pharm","First-Pass Effect","初回通過効果",
  "Time (hr)","Plasma concentration (ug/mL)",c(0,24),c(0,50),
  "初回通過効果のテンプレート。経口投与vs静注の血中濃度差をプロット。","初回通過効果,肝代謝"),
D("loading-maintenance","pharm","Loading & Maintenance Dose","負荷用量・維持用量",
  "Time (hr)","Plasma concentration (ug/mL)",c(0,48),c(0,50),
  "負荷用量と維持用量の血中濃度推移テンプレート。定常状態への迅速な到達をプロット。","負荷用量,維持用量,定常状態"),
D("receptor-occupancy","pharm","Receptor Occupancy","受容体占有率",
  "log [Drug] (M)","Receptor occupancy (%)",c(-9,-3),c(0,100),
  "受容体占有率曲線テンプレート。薬物濃度と受容体占有の関係をプロット。","受容体,占有率,Kd"),
D("therapeutic-index","pharm","Therapeutic Index","治療係数",
  "log Dose (mg/kg)","Cumulative % responding",c(-1,3),c(0,100),
  "治療係数テンプレート。ED50とTD50の比で安全域を評価。","治療係数,TI,安全域",
  sub="Therapeutic / Toxic dose-response"),
D("accumulation-factor","pharm","Accumulation Factor","蓄積係数",
  "Dose number","Css/C1 ratio",c(1,10),c(0,5),
  "蓄積係数テンプレート。反復投与における血中濃度の蓄積をプロット。","蓄積,反復投与,定常状態"),
D("drug-interaction","pharm","Drug Interaction (Synergy)","薬物相互作用（相乗効果）",
  "log [Drug A] (M)","Response (% max)",c(-9,-3),c(0,100),
  "薬物相互作用テンプレート。相乗・相加・拮抗効果の比較をプロット。","相互作用,相乗,拮抗",
  sub="Drug A alone / A+B synergy / A+B antagonism"),
D("clearance","pharm","Clearance Plot","クリアランスプロット",
  "Plasma concentration (ug/mL)","Rate of elimination (ug/hr)",c(0,100),c(0,500),
  "薬物クリアランスのプロット。血中濃度と消失速度の関係をテンプレート。","クリアランス,消失,腎"),
D("dose-adjustment-renal","pharm","Dose Adjustment (Renal)","用量調節（腎機能）",
  "GFR (mL/min)","Dose (% of normal)",c(0,120),c(0,100),
  "腎機能に基づく用量調節テンプレート。GFRと投与量の関係をプロット。","用量調節,腎機能,GFR"),
D("pk-compartment","pharm","PK One-Compartment Model","一次速度モデル",
  "Time (hr)","Amount in body (mg)",c(0,24),c(0,100),
  "一室モデルの薬物動態テンプレート。吸収・分布・消失の動態をプロット。","一室モデル,薬物動態"),
D("inverse-agonist","pharm","Inverse Agonist","逆作動薬",
  "log [Drug] (M)","Response (% basal)",c(-9,-3),c(-50,100),
  "逆作動薬の用量反応曲線テンプレート。構成的活性の抑制をプロット。","逆作動薬,構成的活性",
  hl=list(c(0,"Basal activity"))),
D("time-concentration-routes","pharm","Time-Concentration by Route","投与経路別血中濃度",
  "Time (hr)","Plasma concentration (ug/mL)",c(0,24),c(0,100),
  "投与経路別の血中濃度推移比較テンプレート。IV/IM/SC/PO等を比較。","投与経路,血中濃度",
  sub="IV / IM / SC / Oral"),
D("volume-distribution","pharm","Volume of Distribution","分布容積",
  "Plasma concentration (ug/mL)","Amount in body (mg)",c(0,10),c(0,1000),
  "分布容積（Vd）の概念テンプレート。体内薬物量と血中濃度の関係をプロット。","分布容積,Vd"),

# ================================================================
# MICROBIOLOGY (20)
# ================================================================
D("bacterial-growth","micro","Bacterial Growth Curve","細菌増殖曲線",
  "Time (hr)","CFU/mL (log scale)",c(0,24),c(1e3,1e10),
  "細菌増殖曲線テンプレート。Lag・Log・Stationary・Death phaseをプロット。","増殖曲線,CFU,Lag,Log",ylog=TRUE,
  ann=list(c(3,5e9,"Lag","grey55",3.5),c(9,5e9,"Log","grey55",3.5),c(16,5e9,"Stationary","grey55",3.5),c(22,5e9,"Death","grey55",3.5))),
D("time-kill","micro","Time-Kill Curve","Time-Kill曲線",
  "Time (hr)","log10 CFU/mL",c(0,24),c(0,10),
  "Time-Kill曲線テンプレート。抗菌薬濃度別の殺菌効果を時間経過でプロット。","Time-Kill,殺菌,MIC",
  hl=list(c(3,"99.9% kill (3-log reduction)","#E74C3C")),
  sub="Control / 1x MIC / 2x MIC / 4x MIC"),
D("mic-determination","micro","MIC Determination","MIC測定",
  "Antibiotic concentration (ug/mL)","OD600",c(0,10),c(0,1.5),
  "MIC（最小発育阻止濃度）測定テンプレート。微量液体希釈法での結果をプロット。","MIC,抗菌薬,感受性",
  sub="MIC = lowest conc. with no visible growth"),
D("disk-diffusion","micro","Disk Diffusion","ディスク拡散法",
  "Antibiotic","Zone diameter (mm)",c(0,10),c(0,40),
  "ディスク拡散法（阻止円）テンプレート。抗菌薬ごとの阻止円径をプロット。","ディスク拡散,阻止円,S/I/R",
  hl=list(c(18,"Susceptible (S)","#2E86AB"),c(13,"Intermediate (I)","#F39C12"))),
D("biofilm-formation","micro","Biofilm Formation Curve","バイオフィルム形成曲線",
  "Time (hr)","Biofilm biomass (OD570)",c(0,72),c(0,3),
  "バイオフィルム形成曲線テンプレート。付着・成熟・分散の各段階をプロット。","バイオフィルム,付着,成熟"),
D("virus-growth","micro","One-Step Virus Growth","一段階増殖曲線",
  "Time post-infection (hr)","PFU/mL",c(0,12),c(1e2,1e8),
  "ウイルスの一段階増殖曲線テンプレート。暗黒期・放出期をプロット。","ウイルス,PFU,暗黒期",ylog=TRUE,
  ann=list(c(3,1e3,"Eclipse","grey55",3),c(6,1e3,"Latent","grey55",3),c(9,1e7,"Burst","grey55",3))),
D("pcr-amplification","micro","PCR Amplification Curve","PCR増幅曲線",
  "Cycle number","Fluorescence (RFU)",c(0,40),c(0,5000),
  "リアルタイムPCR増幅曲線テンプレート。Ct値の決定に使用。","PCR,Ct値,増幅"),
D("qpcr","micro","Real-Time qPCR","リアルタイムqPCR",
  "Cycle number","delta Rn",c(0,40),c(0,5),
  "定量PCRテンプレート。複数サンプルのCt値を比較プロット。","qPCR,定量,Ct値",
  hl=list(c(0.2,"Threshold"))),
D("serial-dilution","micro","Serial Dilution Plot","段階希釈プロット",
  "Dilution factor (log)","CFU/plate",c(0,8),c(0,300),
  "段階希釈法による菌数計測テンプレート。希釈倍率と集落数の関係をプロット。","段階希釈,CFU,菌数計測"),
D("temp-growth","micro","Temperature-Growth Rate","温度-増殖速度",
  "Temperature (C)","Growth rate (1/hr)",c(0,60),c(0,2),
  "温度と増殖速度の関係テンプレート。至適温度の決定に使用。","温度,増殖速度,至適温度"),
D("ph-growth","micro","pH-Growth Rate","pH-増殖速度",
  "pH","Growth rate (1/hr)",c(2,10),c(0,2),
  "pHと増殖速度の関係テンプレート。至適pHの決定に使用。","pH,増殖速度,至適pH"),
D("antimicrobial-combo","micro","Antimicrobial Combination (FIC)","抗菌薬併用効果（FIC）",
  "Drug A (fraction of MIC)","Drug B (fraction of MIC)",c(0,1),c(0,1),
  "FICインデックスによる抗菌薬併用効果テンプレート。相乗・相加・拮抗を判定。","FIC,併用効果,相乗",
  sub="Synergy / Additive / Antagonism line"),
D("mutation-rate","micro","Mutation Rate","突然変異率",
  "Generation","Resistant mutant frequency",c(0,100),c(1e-9,1e-3),
  "突然変異率テンプレート。世代数と変異頻度の関係をプロット。","突然変異,耐性,頻度",ylog=TRUE),
D("antibiogram","micro","Antibiogram Template","アンチバイオグラム",
  "Antibiotic","% Susceptible",c(0,10),c(0,100),
  "アンチバイオグラムテンプレート。菌種ごとの抗菌薬感受性パターンをプロット。","アンチバイオグラム,感受性,耐性"),
D("growth-log-phase","micro","Growth Curve (Log Phase)","増殖曲線（対数期）",
  "Time (hr)","ln(OD600)",c(0,8),c(-4,2),
  "対数増殖期のプロットテンプレート。比増殖速度と倍加時間の決定に使用。","対数期,比増殖速度,倍加時間"),
D("sterilization","micro","Sterilization Curve","滅菌曲線",
  "Time (min)","log10 survivors",c(0,30),c(0,8),
  "滅菌曲線テンプレート。D値（decimal reduction time）の決定に使用。","滅菌,D値,死滅速度"),
D("plaque-assay","micro","Plaque Assay","プラークアッセイ",
  "Dilution factor (log)","PFU/mL (log)",c(0,8),c(0,10),
  "プラークアッセイによるウイルス価測定テンプレート。","プラーク,ウイルス価,PFU"),
D("gel-electrophoresis","micro","Gel Electrophoresis","ゲル電気泳動",
  "Migration distance (cm)","log MW (bp)",c(0,10),c(2,5),
  "アガロースゲル電気泳動の分子量推定テンプレート。DNA断片のサイズ推定に使用。","電気泳動,DNA,分子量"),
D("kill-kinetics","micro","Kill Kinetics","殺菌速度論",
  "Time (hr)","Surviving fraction",c(0,6),c(0.001,1),
  "殺菌速度論テンプレート。生残率の時間変化をプロット。","殺菌速度,生残率",ylog=TRUE),
D("cfu-count","micro","CFU Count Plot","CFUカウントプロット",
  "Sample","CFU/mL (log10)",c(0,8),c(0,10),
  "コロニー形成単位（CFU）のカウントプロットテンプレート。","CFU,コロニー,菌数"),

# ================================================================
# IMMUNOLOGY (20)
# ================================================================
D("primary-secondary","immuno","Primary/Secondary Response","一次二次免疫応答",
  "Days after exposure","Antibody titer (AU)",c(0,60),c(0,10000),
  "一次・二次免疫応答テンプレート。抗体価の時間経過と一次/二次の差をプロット。","一次応答,二次応答,抗体価",
  vl=list(c(0,"1st exposure"),c(28,"2nd exposure"))),
D("elisa-standard","immuno","ELISA Standard Curve","ELISA検量線",
  "Concentration (ng/mL)","OD (450 nm)",c(0,1000),c(0,3),
  "ELISA検量線テンプレート。抗原濃度と吸光度の関係をプロット。定量に使用。","ELISA,検量線,吸光度"),
D("ch50","immuno","CH50 Complement Activity","CH50補体活性",
  "Serum dilution","% Hemolysis",c(0,1),c(0,100),
  "CH50補体活性テンプレート。血清希釈と溶血率の関係から補体価を決定。","CH50,補体,溶血",
  hl=list(c(50,"50% hemolysis"))),
D("facs-dot-plot","immuno","Flow Cytometry Dot Plot","フローサイトメトリー散布図",
  "CD4-FITC","CD8-PE",c(0,1000),c(0,1000),
  "フローサイトメトリー散布図テンプレート。CD4/CD8等の二重染色解析に使用。","FACS,フローサイトメトリー,CD4,CD8",
  ann=list(c(200,800,"CD8+","grey55",3),c(800,200,"CD4+","grey55",3),c(800,800,"DP","grey55",3),c(200,200,"DN","grey55",3))),
D("facs-histogram","immuno","Flow Cytometry Histogram","フローサイトメトリーヒストグラム",
  "Fluorescence intensity","Cell count",c(0,1000),c(0,200),
  "フローサイトメトリーヒストグラムテンプレート。蛍光強度の分布をプロット。","FACS,ヒストグラム,蛍光"),
D("antibody-titer","immuno","Antibody Titer Curve","抗体価曲線",
  "Days post-vaccination","Antibody titer (log)",c(0,180),c(0,6),
  "ワクチン接種後の抗体価経時変化テンプレート。IgM・IgG等の推移をプロット。","抗体価,ワクチン,IgG,IgM"),
D("cell-proliferation","immuno","Cell Proliferation Assay","細胞増殖アッセイ",
  "Stimulus concentration","Proliferation index (SI)",c(0,10),c(0,20),
  "リンパ球増殖アッセイテンプレート。刺激濃度と増殖指数の関係をプロット。","増殖アッセイ,リンパ球,SI"),
D("cytotoxicity","immuno","Cytotoxicity Assay","細胞傷害アッセイ",
  "E:T ratio","% Specific lysis",c(0,50),c(0,100),
  "細胞傷害性アッセイテンプレート。E:T比と特異的溶解率の関係をプロット。","細胞傷害,CTL,NK,溶解"),
D("cytokine-profile","immuno","Cytokine Response Profile","サイトカインプロファイル",
  "Time (hr)","Cytokine level (pg/mL)",c(0,72),c(0,1000),
  "サイトカイン応答プロファイルテンプレート。IL-1/TNF/IL-6等の時間経過をプロット。","サイトカイン,TNF,IL-1,IL-6"),
D("ig-levels-age","immuno","Immunoglobulin Levels by Age","年齢別免疫グロブリン値",
  "Age (months)","Ig level (mg/dL)",c(0,60),c(0,1500),
  "年齢別免疫グロブリン値テンプレート。IgG/IgM/IgAの発達変化をプロット。","免疫グロブリン,IgG,IgM,IgA,年齢"),
D("vaccine-response","immuno","Vaccine Response Curve","ワクチン応答曲線",
  "Weeks post-vaccination","IgG titer (AU/mL)",c(0,24),c(0,1000),
  "ワクチン接種後の免疫応答曲線テンプレート。抗体価の上昇と維持をプロット。","ワクチン,免疫応答,IgG"),
D("precipitation","immuno","Precipitation Curve","沈降反応曲線",
  "Antigen concentration","Precipitate (ug)",c(0,10),c(0,100),
  "沈降反応曲線（Heidelberger-Kendall曲線）テンプレート。至適比をプロット。","沈降反応,至適比,抗原抗体"),
D("complement-timeline","immuno","Complement Activation","補体活性化タイムライン",
  "Time (min)","Complement activity (%)",c(0,60),c(0,100),
  "補体活性化の時間経過テンプレート。古典経路・副経路の活性化をプロット。","補体,古典経路,副経路"),
D("affinity-maturation","immuno","Affinity Maturation","親和性成熟",
  "Time (weeks)","Antibody affinity (Ka)",c(0,20),c(1e4,1e10),
  "親和性成熟テンプレート。二次応答での抗体親和性上昇をプロット。","親和性成熟,体細胞変異,胚中心",ylog=TRUE),
D("neutralization","immuno","Neutralization Assay","中和試験",
  "Serum dilution (log)","% Neutralization",c(0,6),c(0,100),
  "中和試験テンプレート。血清希釈と中和率の関係をプロット。","中和,ウイルス,抗体"),
D("western-blot","immuno","Western Blot Template","ウエスタンブロットテンプレート",
  "Lane","Band intensity (AU)",c(0,8),c(0,100),
  "ウエスタンブロットのバンド強度定量テンプレート。","ウエスタンブロット,バンド,定量"),
D("mlr","immuno","Mixed Lymphocyte Reaction","混合リンパ球反応",
  "Stimulator cell number","CPM (3H-thymidine)",c(0,1e5),c(0,50000),
  "混合リンパ球反応テンプレート。刺激細胞数と増殖応答の関係をプロット。","MLR,混合リンパ球,移植"),
D("immunodiffusion","immuno","Radial Immunodiffusion","放射免疫拡散",
  "Antigen concentration (mg/mL)","Ring diameter^2 (mm^2)",c(0,10),c(0,500),
  "放射免疫拡散法テンプレート。抗原濃度とリング直径の関係をプロット。","免疫拡散,Mancini,定量"),
D("hypersensitivity","immuno","Hypersensitivity Timeline","過敏反応タイムライン",
  "Time after exposure","Response intensity",c(0,72),c(0,10),
  "過敏反応の時間経過テンプレート。I-IV型の発症時間の違いをプロット。","過敏反応,I型,IV型",
  sub="Type I / II / III / IV"),
D("lymphocyte-subset","immuno","Lymphocyte Subset","リンパ球サブセット",
  "Cell type","Count (cells/uL)",c(0,6),c(0,3000),
  "リンパ球サブセットのカウントテンプレート。CD4/CD8/B/NK細胞数をプロット。","リンパ球,CD4,CD8,B細胞,NK"),

# ================================================================
# EPIDEMIOLOGY (18)
# ================================================================
D("epidemic-point","epi","Epidemic Curve (Point Source)","流行曲線（点源）",
  "Date","Number of cases",c(0,30),c(0,50),
  "点源型流行曲線テンプレート。一回の曝露による集団発生パターンをプロット。","流行曲線,点源,集団発生"),
D("epidemic-continuous","epi","Epidemic Curve (Continuous)","流行曲線（持続）",
  "Date","Number of cases",c(0,60),c(0,30),
  "持続型流行曲線テンプレート。継続的な曝露による発生パターンをプロット。","流行曲線,持続,曝露"),
D("epidemic-propagated","epi","Epidemic Curve (Propagated)","流行曲線（伝播）",
  "Date","Number of cases",c(0,60),c(0,40),
  "伝播型流行曲線テンプレート。人から人への感染伝播パターンをプロット。","流行曲線,伝播,感染"),
D("2x2-table","epi","2x2 Contingency Table","2x2分割表",
  "","",c(0,4),c(0,4),
  "2x2分割表テンプレート。疫学研究のリスク評価（RR/OR）に使用。","2x2,分割表,RR,OR",
  ann=list(c(1,3,"Disease+","grey55",3),c(3,3,"Disease-","grey55",3),c(1,1.5,"a","grey40",4),c(3,1.5,"b","grey40",4),c(1,0.5,"c","grey40",4),c(3,0.5,"d","grey40",4))),
D("survival-generic","epi","Survival Curve (Generic)","生存曲線（汎用）",
  "Time (months)","Survival probability",c(0,60),c(0,1),
  "汎用生存曲線テンプレート。治療群別の生存確率をプロット。","生存曲線,生存率,予後"),
D("incidence-time","epi","Incidence Rate Over Time","罹患率の推移",
  "Year","Incidence rate (per 100,000)",c(2000,2025),c(0,100),
  "罹患率の経年推移テンプレート。疾患の時間的トレンドをプロット。","罹患率,推移,トレンド"),
D("or-forest","epi","Odds Ratio Forest Plot","オッズ比フォレストプロット",
  "Odds Ratio","Study",c(0.1,10),c(0,10),
  "オッズ比のフォレストプロットテンプレート。メタ分析の結果表示に使用。","オッズ比,フォレストプロット,メタ分析",
  vl=list(c(1,"OR = 1","grey60"))),
D("nnt","epi","Number Needed to Treat","NNT（治療必要数）",
  "Treatment","NNT",c(0,6),c(0,50),
  "NNT（治療必要数）テンプレート。介入効果の臨床的意義を比較。","NNT,治療効果,ARR"),
D("screening","epi","Screening Test Characteristics","スクリーニング検査特性",
  "1 - Specificity","Sensitivity",c(0,1),c(0,1),
  "スクリーニング検査の感度-特異度テンプレート。カットオフ値の最適化に使用。","感度,特異度,スクリーニング"),
D("prevalence-trend","epi","Prevalence Trend","有病率推移",
  "Year","Prevalence (%)",c(2000,2025),c(0,20),
  "有病率の経年推移テンプレート。慢性疾患の疫学トレンドをプロット。","有病率,推移,慢性疾患"),
D("age-standardization","epi","Age Standardization","年齢調整",
  "Age group","Rate (per 100,000)",c(0,8),c(0,200),
  "年齢調整死亡率テンプレート。粗死亡率と年齢調整死亡率の比較に使用。","年齢調整,死亡率,標準化"),
D("cohort-diagram","epi","Cohort Study Diagram","コホート研究図",
  "Time (years)","Cumulative incidence (%)",c(0,10),c(0,50),
  "コホート研究のテンプレート。曝露群と非曝露群の累積罹患率を比較。","コホート,前向き,累積罹患率",
  sub="Exposed / Non-exposed"),
D("case-control","epi","Case-Control Study","症例対照研究",
  "Exposure category","Proportion (%)",c(0,4),c(0,100),
  "症例対照研究テンプレート。症例群と対照群の曝露率を比較。","症例対照,後ろ向き,オッズ比",
  sub="Cases / Controls"),
D("dose-response-epi","epi","Dose-Response (Epidemiological)","用量反応関係（疫学）",
  "Exposure level","Relative risk",c(0,5),c(0,5),
  "疫学的用量反応関係テンプレート。曝露量と相対リスクの関係をプロット。","用量反応,相対リスク,曝露",
  hl=list(c(1,"RR = 1","grey60"))),
D("outbreak-timeline","epi","Outbreak Investigation","アウトブレイク調査タイムライン",
  "Day","Cases / Actions",c(0,30),c(0,20),
  "アウトブレイク調査タイムラインテンプレート。発症者数と対策時期をプロット。","アウトブレイク,調査,介入"),
D("rr-plot","epi","Risk Ratio Plot","リスク比プロット",
  "Risk Ratio","Study",c(0.1,10),c(0,10),
  "リスク比のプロットテンプレート。コホート研究の結果表示に使用。","リスク比,RR,コホート",
  vl=list(c(1,"RR = 1","grey60"))),
D("lead-time-bias","epi","Lead Time Bias","リードタイムバイアス",
  "Time (years)","Survival / Diagnosis",c(0,10),c(0,5),
  "リードタイムバイアスの概念テンプレート。早期診断が見かけの生存期間に与える影響をプロット。","リードタイム,バイアス,スクリーニング"),
D("length-time-bias","epi","Length Time Bias","レングスタイムバイアス",
  "Time","Detected cases",c(0,10),c(0,10),
  "レングスタイムバイアスの概念テンプレート。進行の遅い疾患が多く検出される偏りを示す。","レングスタイム,バイアス"),

# ================================================================
# BIOSTATISTICS (28)
# ================================================================
D("roc-curve","stat","ROC Curve","ROC曲線",
  "1 - Specificity (FPR)","Sensitivity (TPR)",c(0,1),c(0,1),
  "ROC曲線テンプレート。診断検査のAUC（曲線下面積）を評価。","ROC,AUC,感度,特異度",
  ann=list(c(0.5,0.5,"AUC","grey55",4))),
D("kaplan-meier","stat","Kaplan-Meier Curve","カプラン・マイヤー曲線",
  "Time (months)","Survival probability",c(0,60),c(0,1),
  "カプラン・マイヤー生存曲線テンプレート。群間の生存率比較に使用。","Kaplan-Meier,生存曲線,ログランク",
  sub="Group A / Group B"),
D("forest-plot","stat","Forest Plot","フォレストプロット",
  "Effect size (OR / HR / RR)","Study",c(0.1,10),c(0,10),
  "フォレストプロットテンプレート。メタ分析の個別研究結果と統合効果をプロット。","フォレストプロット,メタ分析,統合効果",
  vl=list(c(1,"Null effect"))),
D("bland-altman","stat","Bland-Altman Plot","ブランド・アルトマンプロット",
  "Mean of two methods","Difference between methods",c(0,100),c(-20,20),
  "ブランド・アルトマンプロットテンプレート。2測定法の一致度を評価。","Bland-Altman,一致度,測定法比較",
  hl=list(c(0,"Mean difference"))),
D("calibration-plot","stat","Calibration Plot","較正プロット",
  "Predicted probability","Observed probability",c(0,1),c(0,1),
  "較正プロットテンプレート。予測モデルの精度をプロット。45度線からの乖離を評価。","較正,予測モデル,精度"),
D("funnel-plot","stat","Funnel Plot","ファネルプロット",
  "Effect size","Standard error",c(-2,2),c(0,1),
  "ファネルプロットテンプレート。出版バイアスの検出に使用。","ファネルプロット,出版バイアス,メタ分析"),
D("qq-plot","stat","Q-Q Plot","Q-Qプロット",
  "Theoretical quantiles","Sample quantiles",c(-3,3),c(-3,3),
  "Q-Qプロットテンプレート。データの正規性を視覚的に評価。","Q-Q,正規性,分布"),
D("residual-plot","stat","Residual Plot","残差プロット",
  "Fitted values","Residuals",c(0,100),c(-30,30),
  "残差プロットテンプレート。回帰モデルの妥当性を評価。","残差,回帰,モデル診断",
  hl=list(c(0,""))),
D("scatter-regression","stat","Scatter Plot with Regression","散布図＋回帰直線",
  "X variable","Y variable",c(0,100),c(0,100),
  "散布図＋回帰直線テンプレート。2変数の線形関係と回帰式をプロット。","散布図,回帰,相関"),
D("box-plot","stat","Box Plot","箱ひげ図",
  "Group","Value",c(0,4),c(0,100),
  "箱ひげ図テンプレート。群間のデータ分布を比較。中央値・四分位範囲を表示。","箱ひげ図,中央値,四分位"),
D("box-plot-grouped","stat","Grouped Box Plot","グループ別箱ひげ図",
  "Category","Value",c(0,6),c(0,100),
  "グループ別箱ひげ図テンプレート。複数群×複数条件の比較に使用。","箱ひげ図,グループ,比較"),
D("violin-plot","stat","Violin Plot","バイオリンプロット",
  "Group","Value",c(0,4),c(0,100),
  "バイオリンプロットテンプレート。データの分布形状を詳細に可視化。","バイオリン,分布,密度"),
D("histogram-template","stat","Histogram","ヒストグラム",
  "Value","Frequency",c(0,100),c(0,30),
  "ヒストグラムテンプレート。データの度数分布を可視化。","ヒストグラム,度数分布,頻度"),
D("bar-error","stat","Bar Chart with Error Bars","棒グラフ＋エラーバー",
  "Group","Mean +/- SE",c(0,5),c(0,100),
  "棒グラフ＋エラーバーテンプレート。群間の平均値比較に使用。","棒グラフ,エラーバー,平均値,SE"),
D("heatmap-template","stat","Heatmap","ヒートマップ",
  "Variable 1","Variable 2",c(0,10),c(0,10),
  "ヒートマップテンプレート。変数間の関係を色で可視化。","ヒートマップ,色,可視化"),
D("waterfall-plot","stat","Waterfall Plot","ウォーターフォールプロット",
  "Patient","% Change from baseline",c(0,20),c(-100,100),
  "ウォーターフォールプロットテンプレート。腫瘍縮小率等を個別にプロット。","ウォーターフォール,腫瘍縮小,RECIST",
  hl=list(c(-30,"PR threshold","#2E86AB"),c(20,"PD threshold","#E74C3C"))),
D("swimmer-plot","stat","Swimmer Plot","スイマープロット",
  "Time (months)","Patient",c(0,36),c(0,20),
  "スイマープロットテンプレート。個々の患者の治療経過を横棒でプロット。","スイマープロット,治療経過,腫瘍"),
D("dca","stat","Decision Curve Analysis","決定曲線分析",
  "Threshold probability","Net benefit",c(0,1),c(-0.1,0.5),
  "決定曲線分析（DCA）テンプレート。予測モデルの臨床的有用性を評価。","DCA,決定曲線,ネットベネフィット"),
D("cumulative-incidence","stat","Cumulative Incidence","累積発生率",
  "Time (months)","Cumulative incidence",c(0,60),c(0,1),
  "累積発生率テンプレート。競合リスク存在下での事象発生率をプロット。","累積発生率,競合リスク"),
D("competing-risks","stat","Competing Risks","競合リスク",
  "Time (months)","Cumulative incidence",c(0,60),c(0,1),
  "競合リスクテンプレート。複数の事象を同時に評価。","競合リスク,Fine-Gray,累積発生率",
  sub="Event of interest / Competing event"),
D("subgroup-forest","stat","Subgroup Analysis","サブグループ解析",
  "Hazard ratio","Subgroup",c(0.1,10),c(0,8),
  "サブグループ解析フォレストプロットテンプレート。","サブグループ,フォレストプロット,HR",
  vl=list(c(1,"HR = 1"))),
D("tornado-plot","stat","Sensitivity Tornado Plot","感度解析トルネードプロット",
  "Effect on outcome","Parameter",c(-50,50),c(0,8),
  "感度解析トルネードプロットテンプレート。各パラメータの影響度を比較。","感度解析,トルネード,パラメータ"),
D("passing-bablok","stat","Passing-Bablok Regression","パッシング・バブロック回帰",
  "Method A","Method B",c(0,100),c(0,100),
  "パッシング・バブロック回帰テンプレート。2測定法の比較に使用。","パッシング・バブロック,方法比較"),
D("levey-jennings","stat","Levey-Jennings QC Chart","レビー・ジェニングスQC管理図",
  "Run number","Measured value",c(0,30),c(-4,4),
  "レビー・ジェニングスQC管理図テンプレート。分析精度の品質管理に使用。","レビー・ジェニングス,QC,品質管理",
  hl=list(c(0,"Mean","grey50"),c(2,"+2SD","#F39C12"),c(-2,"-2SD","#F39C12"),c(3,"+3SD","#E74C3C"),c(-3,"-3SD","#E74C3C"))),
D("correlation-matrix","stat","Correlation Matrix","相関行列",
  "Variable","Variable",c(0,8),c(0,8),
  "相関行列テンプレート。多変量間の相関係数をヒートマップで可視化。","相関,行列,ヒートマップ"),
D("bubble-plot","stat","Bubble Plot","バブルプロット",
  "X variable","Y variable",c(0,100),c(0,100),
  "バブルプロットテンプレート。3変数を位置とサイズで同時に可視化。","バブル,3変数,サイズ"),
D("spider-plot","stat","Spider/Radar Plot","スパイダー/レーダーチャート",
  "Angle","Value",c(0,360),c(0,10),
  "スパイダー（レーダー）チャートテンプレート。多次元データの比較に使用。","スパイダー,レーダー,多次元"),
D("bland-altman-ratio","stat","Bland-Altman (Ratio)","ブランド・アルトマン（比）",
  "Mean of two methods","Ratio of methods",c(0,100),c(0.5,2),
  "比型ブランド・アルトマンプロットテンプレート。対数変換データの一致度評価に使用。","Bland-Altman,比,対数"),

# ================================================================
# CARDIOLOGY (22)
# ================================================================
D("ecg-normal","cardio","Normal ECG","正常心電図",
  "Time (ms)","Amplitude (mV)",c(0,1000),c(-1,2),
  "正常心電図テンプレート。P-QRS-T波形の各要素をプロット。","ECG,心電図,P波,QRS,T波",
  ann=list(c(100,1.5,"P","grey55",3),c(250,1.8,"QRS","grey55",3),c(500,1.5,"T","grey55",3)),
  hl=list(c(0,"Baseline"))),
D("ecg-st-elevation","cardio","ECG: ST Elevation","心電図：ST上昇",
  "Time (ms)","Amplitude (mV)",c(0,1000),c(-1,3),
  "ST上昇型心電図テンプレート。急性心筋梗塞のST変化をプロット。","ECG,ST上昇,STEMI,心筋梗塞"),
D("ecg-st-depression","cardio","ECG: ST Depression","心電図：ST低下",
  "Time (ms)","Amplitude (mV)",c(0,1000),c(-2,2),
  "ST低下型心電図テンプレート。虚血性変化のST低下をプロット。","ECG,ST低下,虚血"),
D("ecg-afib","cardio","ECG: Atrial Fibrillation","心電図：心房細動",
  "Time (ms)","Amplitude (mV)",c(0,3000),c(-1,2),
  "心房細動の心電図テンプレート。不整なRR間隔とf波をプロット。","ECG,心房細動,Af,不整脈"),
D("ecg-1st-block","cardio","ECG: 1st Degree AV Block","心電図：1度房室ブロック",
  "Time (ms)","Amplitude (mV)",c(0,1000),c(-1,2),
  "1度房室ブロックの心電図テンプレート。PR間隔延長をプロット。","ECG,房室ブロック,PR延長"),
D("ecg-2nd-block","cardio","ECG: 2nd Degree AV Block","心電図：2度房室ブロック",
  "Time (ms)","Amplitude (mV)",c(0,2000),c(-1,2),
  "2度房室ブロックの心電図テンプレート。Wenckebach/Mobitz II型をプロット。","ECG,2度房室ブロック,Wenckebach"),
D("ecg-3rd-block","cardio","ECG: 3rd Degree AV Block","心電図：3度房室ブロック",
  "Time (ms)","Amplitude (mV)",c(0,3000),c(-1,2),
  "3度（完全）房室ブロックの心電図テンプレート。P波とQRSの解離をプロット。","ECG,完全房室ブロック,解離"),
D("ecg-long-qt","cardio","ECG: Long QT","心電図：QT延長",
  "Time (ms)","Amplitude (mV)",c(0,1000),c(-1,2),
  "QT延長症候群の心電図テンプレート。延長したQT間隔をプロット。","ECG,QT延長,LQTS"),
D("arterial-pressure","cardio","Arterial Pressure Waveform","動脈圧波形",
  "Time (s)","Pressure (mmHg)",c(0,3),c(0,160),
  "動脈圧波形テンプレート。収縮期・拡張期圧とnotchをプロット。","動脈圧,波形,収縮期,拡張期"),
D("cvp","cardio","Central Venous Pressure","中心静脈圧",
  "Time (s)","CVP (mmHg)",c(0,3),c(-2,15),
  "中心静脈圧波形テンプレート。a/c/v波をプロット。","CVP,中心静脈圧,波形",
  ann=list(c(0.3,10,"a","grey55",3),c(0.8,5,"c","grey55",3),c(1.5,8,"v","grey55",3))),
D("pa-pressure","cardio","Pulmonary Artery Pressure","肺動脈圧",
  "Time (s)","Pressure (mmHg)",c(0,3),c(0,40),
  "肺動脈圧波形テンプレート。収縮期・拡張期の肺動脈圧をプロット。","肺動脈圧,波形"),
D("pcwp","cardio","PCWP Tracing","肺動脈楔入圧",
  "Time (s)","PCWP (mmHg)",c(0,3),c(0,25),
  "肺動脈楔入圧テンプレート。左房圧の間接的測定をプロット。","PCWP,楔入圧,左房圧"),
D("jvp","cardio","Jugular Venous Pulse","頸静脈波",
  "Time (s)","Amplitude",c(0,2),c(0,10),
  "頸静脈波テンプレート。a/c/v波とx/y谷をプロット。","JVP,頸静脈,a波,v波"),
D("coronary-flow","cardio","Coronary Flow","冠血流量",
  "Aortic pressure (mmHg)","Coronary blood flow (mL/min)",c(40,160),c(0,300),
  "冠血流自動調節テンプレート。灌流圧と冠血流の関係をプロット。","冠血流,自動調節,圧-流量"),
D("aortic-stenosis","cardio","Aortic Stenosis Gradient","大動脈弁狭窄圧較差",
  "Time (ms)","Pressure (mmHg)",c(0,500),c(0,200),
  "大動脈弁狭窄症の圧較差テンプレート。左室圧と大動脈圧の差をプロット。","大動脈弁狭窄,圧較差,AS"),
D("cardiac-cycle","cardio","Cardiac Cycle Events","心周期イベント",
  "Time (ms)","Pressure (mmHg)",c(0,800),c(0,130),
  "心周期の主要イベントテンプレート。弁開閉のタイミングをプロット。","心周期,弁,開閉"),
D("thermodilution","cardio","Thermodilution Curve","熱希釈曲線",
  "Time (s)","Temperature change (C)",c(0,15),c(-1,0),
  "熱希釈法による心拍出量測定テンプレート。温度変化曲線をプロット。","熱希釈,心拍出量,Swan-Ganz"),
D("preload-afterload","cardio","Preload-Afterload Interaction","前負荷-後負荷相互作用",
  "End-diastolic volume (mL)","Stroke volume (mL)",c(50,200),c(0,120),
  "前負荷と後負荷の相互作用テンプレート。心機能曲線の変化をプロット。","前負荷,後負荷,心機能",
  sub="Normal / Increased afterload / Heart failure"),
D("bp-waveform","cardio","Blood Pressure Waveform","血圧波形",
  "Time (s)","Pressure (mmHg)",c(0,5),c(0,160),
  "血圧波形テンプレート。動脈血圧の経時変化をモニタリング。","血圧,波形,モニタリング"),
D("ecg-vt","cardio","ECG: Ventricular Tachycardia","心電図：心室頻拍",
  "Time (ms)","Amplitude (mV)",c(0,3000),c(-2,2),
  "心室頻拍の心電図テンプレート。幅広QRS波形の連続をプロット。","ECG,心室頻拍,VT"),
D("ecg-aflutter","cardio","ECG: Atrial Flutter","心電図：心房粗動",
  "Time (ms)","Amplitude (mV)",c(0,2000),c(-1,2),
  "心房粗動の心電図テンプレート。鋸歯状のflutter波をプロット。","ECG,心房粗動,AFL,鋸歯状"),
D("mitral-stenosis","cardio","Mitral Stenosis Gradient","僧帽弁狭窄圧較差",
  "Time (ms)","Pressure (mmHg)",c(0,500),c(0,40),
  "僧帽弁狭窄症の圧較差テンプレート。左房圧と左室拡張期圧の差をプロット。","僧帽弁狭窄,圧較差,MS"),

# ================================================================
# PULMONOLOGY (15)
# ================================================================
D("spirometry-normal","pulm","Spirometry (Normal)","スパイロメトリー（正常）",
  "Time (s)","Volume (L)",c(0,8),c(0,5),
  "正常スパイロメトリーテンプレート。FVC・FEV1の正常パターンをプロット。","スパイロメトリー,FVC,FEV1,正常"),
D("spirometry-obstructive","pulm","Spirometry (Obstructive)","スパイロメトリー（閉塞性）",
  "Time (s)","Volume (L)",c(0,8),c(0,5),
  "閉塞性パターンのスパイロメトリーテンプレート。FEV1/FVC低下をプロット。","閉塞性,COPD,喘息,FEV1/FVC",
  sub="Normal / Obstructive pattern"),
D("spirometry-restrictive","pulm","Spirometry (Restrictive)","スパイロメトリー（拘束性）",
  "Time (s)","Volume (L)",c(0,8),c(0,5),
  "拘束性パターンのスパイロメトリーテンプレート。FVC低下をプロット。","拘束性,肺線維症,FVC低下",
  sub="Normal / Restrictive pattern"),
D("flow-volume-normal","pulm","Flow-Volume (Normal)","フローボリューム（正常）",
  "Volume (L)","Flow (L/s)",c(0,6),c(-8,12),
  "正常フローボリュームループテンプレート。呼気・吸気のパターンをプロット。","フローボリューム,正常",
  hl=list(c(0,""))),
D("flow-volume-obstruct","pulm","Flow-Volume (Obstructive)","フローボリューム（閉塞性）",
  "Volume (L)","Flow (L/s)",c(0,6),c(-8,12),
  "閉塞性フローボリュームループテンプレート。呼気流量低下のパターンをプロット。","フローボリューム,閉塞性,COPD"),
D("flow-volume-restrict","pulm","Flow-Volume (Restrictive)","フローボリューム（拘束性）",
  "Volume (L)","Flow (L/s)",c(0,4),c(-8,12),
  "拘束性フローボリュームループテンプレート。肺容量減少のパターンをプロット。","フローボリューム,拘束性"),
D("flow-volume-uao","pulm","Flow-Volume (Upper Airway)","フローボリューム（上気道閉塞）",
  "Volume (L)","Flow (L/s)",c(0,6),c(-8,12),
  "上気道閉塞のフローボリュームテンプレート。固定性/可変性閉塞のパターンをプロット。","上気道閉塞,固定性,可変性"),
D("chest-wall-compliance","pulm","Chest Wall Compliance","胸壁コンプライアンス",
  "Pressure (cmH2O)","Volume (L)",c(-20,40),c(0,6),
  "胸壁コンプライアンス曲線テンプレート。胸壁の圧-容量関係をプロット。","胸壁,コンプライアンス"),
D("total-compliance","pulm","Total Respiratory Compliance","呼吸系総コンプライアンス",
  "Pressure (cmH2O)","Volume (L)",c(-20,40),c(0,6),
  "呼吸系総コンプライアンステンプレート。肺+胸壁の合計をプロット。","呼吸系,コンプライアンス",
  sub="Lung / Chest wall / Total"),
D("work-breathing","pulm","Work of Breathing","呼吸仕事量",
  "Volume (L)","Pressure (cmH2O)",c(0,6),c(-10,20),
  "呼吸仕事量テンプレート。圧-容量曲線で囲まれた面積を評価。","呼吸仕事量,圧-容量"),
D("o2-co2-diagram","pulm","O2-CO2 Diagram","O2-CO2ダイアグラム",
  "PO2 (mmHg)","PCO2 (mmHg)",c(0,150),c(0,60),
  "O2-CO2ダイアグラムテンプレート。換気と灌流の関係を評価。","O2-CO2,ガス交換,V/Q"),
D("capnography-wave","pulm","Capnography Waveform","カプノグラフィー波形",
  "Time (s)","EtCO2 (mmHg)",c(0,10),c(0,50),
  "カプノグラフィー波形テンプレート。呼気CO2のモニタリングに使用。","カプノグラフィー,EtCO2"),
D("ventilator-waveform","pulm","Ventilator Waveform","人工呼吸器波形",
  "Time (s)","Pressure (cmH2O) / Flow (L/min)",c(0,6),c(-30,40),
  "人工呼吸器の圧・流量波形テンプレート。","人工呼吸器,圧波形,流量波形"),
D("dead-space","pulm","Dead Space Calculation","死腔計算",
  "Expired volume (mL)","CO2 concentration (%)",c(0,500),c(0,5),
  "死腔計算テンプレート。Fowler法による解剖学的死腔の決定に使用。","死腔,Fowler,解剖学的"),
D("lung-compliance-disease","pulm","Lung Compliance (Disease)","肺コンプライアンス（疾患）",
  "Pressure (cmH2O)","Volume (L)",c(0,30),c(0,6),
  "疾患別肺コンプライアンス比較テンプレート。正常/線維症/肺気腫を比較。","コンプライアンス,線維症,肺気腫",
  sub="Normal / Fibrosis / Emphysema"),

# ================================================================
# NEPHROLOGY (15)
# ================================================================
D("gfr-measurement","nephro","GFR Measurement","GFR測定",
  "Time (hr)","Plasma inulin (mg/dL)",c(0,6),c(0,100),
  "GFR測定テンプレート。イヌリンクリアランスによる糸球体濾過量の評価。","GFR,イヌリン,クリアランス"),
D("creatinine-clearance","nephro","Creatinine Clearance","クレアチニンクリアランス",
  "Time","Serum creatinine (mg/dL)",c(0,10),c(0,10),
  "クレアチニンクリアランステンプレート。腎機能の経時的評価に使用。","クレアチニン,クリアランス,腎機能"),
D("glucose-titration","nephro","Glucose Titration (TmG)","ブドウ糖滴定曲線（TmG）",
  "Plasma glucose (mg/dL)","Glucose handling (mg/min)",c(0,600),c(0,600),
  "ブドウ糖滴定曲線テンプレート。濾過・再吸収・排泄の関係をプロット。","TmG,再吸収,糖尿",
  sub="Filtered / Reabsorbed / Excreted"),
D("pah-titration","nephro","PAH Titration","PAH滴定曲線",
  "Plasma PAH (mg/dL)","PAH handling (mg/min)",c(0,60),c(0,600),
  "PAH滴定曲線テンプレート。腎血漿流量（RPF）とTmPAHの決定に使用。","PAH,RPF,分泌,TmPAH"),
D("acidbase-nomogram","nephro","Acid-Base Nomogram","酸塩基平衡ノモグラム",
  "pH","HCO3- (mEq/L)",c(7.0,7.6),c(5,45),
  "酸塩基平衡ノモグラムテンプレート。pH/HCO3-/PCO2の関係を評価。","酸塩基,pH,HCO3,PCO2"),
D("davenport","nephro","Davenport Diagram","ダベンポートダイアグラム",
  "pH","HCO3- (mEq/L)",c(7.0,7.6),c(5,45),
  "ダベンポートダイアグラムテンプレート。酸塩基障害の病態を図示。","ダベンポート,酸塩基,代償"),
D("anion-gap","nephro","Anion Gap","アニオンギャップ",
  "Component","mEq/L",c(0,4),c(0,150),
  "アニオンギャップのテンプレート。血清電解質の構成をプロット。","アニオンギャップ,AG,代謝性アシドーシス"),
D("rta-comparison","nephro","RTA Comparison","RTA比較",
  "Type","Serum K+ / pH / HCO3-",c(0,4),c(0,10),
  "尿細管性アシドーシス（RTA）の型比較テンプレート。I/II/IV型を比較。","RTA,尿細管性アシドーシス,比較"),
D("urine-concentration","nephro","Urine Concentration","尿濃縮",
  "Flow rate (mL/min)","Urine osmolality (mOsm/kg)",c(0,20),c(0,1200),
  "尿濃縮テンプレート。尿流量と尿浸透圧の関係をプロット。ADHの影響を評価。","尿濃縮,浸透圧,ADH"),
D("adh-response","nephro","ADH Response","ADH応答",
  "Plasma osmolality (mOsm/kg)","Plasma ADH (pg/mL)",c(275,310),c(0,10),
  "ADH応答テンプレート。血漿浸透圧とADH分泌の関係をプロット。","ADH,浸透圧,分泌"),
D("aldosterone-response","nephro","Aldosterone Response","アルドステロン応答",
  "Plasma K+ (mEq/L)","Aldosterone (ng/dL)",c(3,6),c(0,30),
  "アルドステロン応答テンプレート。カリウム濃度とアルドステロン分泌の関係をプロット。","アルドステロン,カリウム,RAAS"),
D("rpf","nephro","Renal Plasma Flow","腎血漿流量",
  "Renal perfusion pressure (mmHg)","RPF (mL/min)",c(0,200),c(0,700),
  "腎血漿流量テンプレート。灌流圧とRPFの関係をプロット。","RPF,腎血漿流量"),
D("filtration-fraction","nephro","Filtration Fraction","濾過率",
  "Renal artery pressure (mmHg)","GFR or RPF (mL/min)",c(0,200),c(0,700),
  "濾過率テンプレート。GFRとRPFの比をプロット。","濾過率,FF,GFR,RPF",
  sub="GFR / RPF / Filtration fraction"),
D("bun-cr-ratio","nephro","BUN/Cr Ratio","BUN/Cr比",
  "Condition","BUN/Cr ratio",c(0,5),c(0,40),
  "BUN/Cr比テンプレート。腎前性/腎性/腎後性の鑑別に使用。","BUN,クレアチニン,比,鑑別"),
D("raas","nephro","RAAS Response","RAAS応答",
  "Blood pressure (mmHg)","Renin / Angiotensin / Aldosterone",c(60,140),c(0,10),
  "レニン-アンジオテンシン-アルドステロン系応答テンプレート。血圧との関係をプロット。","RAAS,レニン,アンジオテンシン"),

# ================================================================
# ENDOCRINOLOGY (18)
# ================================================================
D("ogtt","endo","OGTT Curve","OGTT（経口ブドウ糖負荷試験）",
  "Time (min)","Blood glucose (mg/dL)",c(0,120),c(0,300),
  "OGTT曲線テンプレート。75gブドウ糖負荷後の血糖変化をプロット。","OGTT,血糖,糖尿病",
  hl=list(c(200,"DM threshold (2h)","#E74C3C"),c(140,"IGT threshold (2h)","#F39C12")),
  xb=c(0,30,60,90,120)),
D("ogtt-insulin","endo","OGTT + Insulin","OGTT＋インスリン",
  "Time (min)","Blood glucose (mg/dL) / Insulin (uU/mL)",c(0,120),c(0,300),
  "OGTT＋インスリン同時測定テンプレート。血糖とインスリンの応答を比較。","OGTT,インスリン,血糖",
  sub="Glucose / Insulin",xb=c(0,30,60,90,120)),
D("insulin-response","endo","Insulin Response","インスリン応答",
  "Time (min)","Plasma insulin (uU/mL)",c(0,120),c(0,200),
  "インスリン応答テンプレート。糖負荷後のインスリン分泌パターンをプロット。","インスリン,分泌,ベータ細胞"),
D("tsh-feedback","endo","TSH Feedback","TSHフィードバック",
  "Free T4 (ng/dL)","TSH (mIU/L)",c(0,4),c(0,50),
  "TSH-T4フィードバックテンプレート。甲状腺ホルモンの負のフィードバックをプロット。","TSH,T4,フィードバック,甲状腺"),
D("cortisol-diurnal","endo","Cortisol Diurnal Rhythm","コルチゾール日内変動",
  "Time of day (hr)","Cortisol (ug/dL)",c(0,24),c(0,25),
  "コルチゾール日内変動テンプレート。朝高値・夜低値のパターンをプロット。","コルチゾール,日内変動,概日リズム",
  xb=c(0,4,8,12,16,20,24)),
D("gh-pulsatile","endo","GH Pulsatile Secretion","成長ホルモン拍動性分泌",
  "Time (hr)","GH (ng/mL)",c(0,24),c(0,30),
  "成長ホルモンの拍動性分泌テンプレート。睡眠時の分泌ピークをプロット。","GH,成長ホルモン,拍動性"),
D("dexamethasone","endo","Dexamethasone Suppression","デキサメタゾン抑制試験",
  "Time point","Cortisol (ug/dL)",c(0,4),c(0,25),
  "デキサメタゾン抑制試験テンプレート。正常応答とクッシング症候群の比較。","デキサメタゾン,抑制試験,クッシング",
  sub="Normal / Cushing disease"),
D("glucose-clamp","endo","Glucose Clamp","グルコースクランプ",
  "Time (min)","Glucose infusion rate (mg/kg/min)",c(0,180),c(0,15),
  "グルコースクランプテンプレート。インスリン感受性の定量評価に使用。","グルコースクランプ,インスリン感受性"),
D("hba1c-glucose","endo","HbA1c-Glucose Correlation","HbA1c-血糖相関",
  "HbA1c (%)","Estimated average glucose (mg/dL)",c(4,12),c(50,350),
  "HbA1c-平均血糖相関テンプレート。HbA1cと血糖値の対応関係をプロット。","HbA1c,血糖,相関"),
D("calcium-pth","endo","Calcium-PTH Relationship","カルシウム-PTH関係",
  "Serum calcium (mg/dL)","PTH (pg/mL)",c(6,14),c(0,200),
  "カルシウム-PTH関係テンプレート。血清Caの変化に対するPTH応答をプロット。","カルシウム,PTH,副甲状腺"),
D("insulin-tolerance","endo","Insulin Tolerance Test","インスリン負荷試験",
  "Time (min)","Blood glucose (mg/dL)",c(0,120),c(0,120),
  "インスリン負荷試験テンプレート。GH・コルチゾール分泌の誘発に使用。","インスリン負荷,低血糖,GH"),
D("water-deprivation","endo","Water Deprivation Test","水制限試験",
  "Time (hr)","Urine osmolality (mOsm/kg)",c(0,8),c(0,1200),
  "水制限試験テンプレート。尿崩症の鑑別に使用。","水制限,尿崩症,ADH"),
D("thyroid-levels","endo","Thyroid Hormone Levels","甲状腺ホルモン値",
  "Condition","T3 / T4 / TSH level",c(0,5),c(0,10),
  "甲状腺ホルモン値テンプレート。甲状腺機能亢進/低下の検査値パターンをプロット。","甲状腺,T3,T4,TSH"),
D("tanner-stages","endo","Tanner Stages Timeline","タナーステージタイムライン",
  "Age (years)","Tanner stage",c(8,18),c(1,5),
  "タナーステージタイムラインテンプレート。思春期の発達段階をプロット。","タナー,思春期,発達",
  yb=c(1,2,3,4,5)),
D("acth-stimulation","endo","ACTH Stimulation Test","ACTH負荷試験",
  "Time (min)","Cortisol (ug/dL)",c(0,60),c(0,30),
  "ACTH負荷試験テンプレート。副腎機能の評価に使用。","ACTH,コルチゾール,副腎",
  sub="Normal / Adrenal insufficiency"),
D("gnrh-pulse","endo","GnRH Pulse Pattern","GnRHパルスパターン",
  "Time (hr)","LH (mIU/mL)",c(0,24),c(0,30),
  "GnRHパルスパターンテンプレート。LH拍動性分泌をプロット。","GnRH,LH,パルス,性腺"),
D("growth-hormone-stim","endo","GH Stimulation Test","成長ホルモン負荷試験",
  "Time (min)","GH (ng/mL)",c(0,120),c(0,30),
  "GH負荷試験テンプレート。GH分泌不全症の診断に使用。","GH,負荷試験,成長ホルモン",
  hl=list(c(6,"Cut-off (6 ng/mL)","#E74C3C")),xb=c(0,30,60,90,120)),
D("menstrual-cycle","endo","Menstrual Cycle Hormones","月経周期ホルモン",
  "Day of cycle","Hormone level",c(1,28),c(0,10),
  "月経周期のホルモン変動テンプレート。FSH/LH/E2/Progesteroneの推移をプロット。","月経周期,FSH,LH,エストロゲン,プロゲステロン",
  sub="FSH / LH / Estradiol / Progesterone"),

# ================================================================
# GASTROENTEROLOGY (12)
# ================================================================
D("gastric-acid","gi","Gastric Acid Secretion","胃酸分泌曲線",
  "Time (min)","Acid output (mEq/hr)",c(0,120),c(0,40),
  "胃酸分泌曲線テンプレート。基礎分泌と刺激後分泌をプロット。","胃酸,BAO,MAO,分泌"),
D("intestinal-absorption","gi","Intestinal Absorption","腸管吸収曲線",
  "Position along intestine","Absorption rate",c(0,10),c(0,10),
  "腸管部位別吸収曲線テンプレート。栄養素の吸収部位と効率をプロット。","腸管,吸収,小腸"),
D("lft-panel","gi","LFT Panel","肝機能検査パネル",
  "Test","Value (U/L or mg/dL)",c(0,7),c(0,500),
  "肝機能検査パネルテンプレート。AST/ALT/ALP/T-Bil/Alb等をプロット。","肝機能,AST,ALT,ALP"),
D("child-pugh","gi","Child-Pugh Score","チャイルド・ピュースコア",
  "Parameter","Score (1-3)",c(0,6),c(0,3),
  "チャイルド・ピュースコアテンプレート。肝硬変の重症度評価に使用。","Child-Pugh,肝硬変,予後"),
D("meld-score","gi","MELD Score","MELDスコア",
  "Component","Value",c(0,4),c(0,40),
  "MELDスコアテンプレート。肝移植の優先度評価に使用。","MELD,肝移植,予後"),
D("esophageal-ph","gi","Esophageal pH Monitoring","食道pH測定",
  "Time (hr)","pH",c(0,24),c(0,8),
  "24時間食道pHモニタリングテンプレート。GERDの診断に使用。","食道pH,GERD,逆流",
  hl=list(c(4,"pH 4 threshold","#E74C3C"))),
D("gastric-emptying","gi","Gastric Emptying","胃排出曲線",
  "Time (min)","Retention (%)",c(0,240),c(0,100),
  "胃排出曲線テンプレート。食後の胃内残留率の経時変化をプロット。","胃排出,残留率,胃不全麻痺"),
D("hydrogen-breath","gi","Hydrogen Breath Test","水素呼気試験",
  "Time (min)","H2 (ppm)",c(0,180),c(0,100),
  "水素呼気試験テンプレート。乳糖不耐症やSIBOの診断に使用。","水素呼気,乳糖不耐症,SIBO",
  xb=c(0,30,60,90,120,150,180)),
D("bilirubin-metabolism","gi","Bilirubin Metabolism","ビリルビン代謝",
  "Stage","Bilirubin (mg/dL)",c(0,5),c(0,20),
  "ビリルビン代謝テンプレート。直接型/間接型の比較に使用。","ビリルビン,直接型,間接型,黄疸"),
D("liver-elastography","gi","Liver Elastography","肝エラストグラフィー",
  "Fibrosis stage","Liver stiffness (kPa)",c(0,5),c(0,40),
  "肝エラストグラフィーテンプレート。肝線維化ステージと硬度の関係をプロット。","エラストグラフィー,肝線維化,硬度"),
D("pancreatic-function","gi","Pancreatic Function","膵機能検査",
  "Time (min)","Enzyme output",c(0,120),c(0,100),
  "膵機能検査テンプレート。セクレチン/CCK負荷後の膵外分泌機能を評価。","膵機能,外分泌,セクレチン"),
D("intestinal-transit","gi","Intestinal Transit Time","腸管通過時間",
  "Time (hr)","Position along GI tract",c(0,72),c(0,10),
  "腸管通過時間テンプレート。消化管各部位の通過時間をプロット。","通過時間,蠕動,消化管"),

# ================================================================
# HEMATOLOGY (18)
# ================================================================
D("cbc-reference","hemato","CBC Reference Ranges","CBC基準値",
  "Parameter","Value",c(0,8),c(0,20),
  "CBC（全血球算定）基準値テンプレート。各血球系の基準範囲をプロット。","CBC,基準値,WBC,Hb,Plt"),
D("hb-electrophoresis","hemato","Hemoglobin Electrophoresis","ヘモグロビン電気泳動",
  "Migration distance","Density",c(0,10),c(0,10),
  "ヘモグロビン電気泳動テンプレート。HbA/HbS/HbC等の分離パターンをプロット。","ヘモグロビン,電気泳動,HbS"),
D("iron-studies","hemato","Iron Studies Panel","鉄代謝パネル",
  "Parameter","Value",c(0,5),c(0,500),
  "鉄代謝パネルテンプレート。Fe/TIBC/フェリチン/TSAT等をプロット。","鉄,TIBC,フェリチン,貧血"),
D("coagulation-cascade","hemato","Coagulation Cascade","凝固カスケード",
  "Time","Factor activity (%)",c(0,10),c(0,100),
  "凝固カスケードテンプレート。各凝固因子の活性を時間経過でプロット。","凝固,カスケード,因子"),
D("pt-inr","hemato","PT/INR Monitoring","PT/INRモニタリング",
  "Day","INR",c(0,14),c(0,5),
  "PT/INRモニタリングテンプレート。ワーファリン投与中のINR推移をプロット。","PT,INR,ワーファリン,抗凝固",
  hl=list(c(2,"Target INR low","#2E86AB"),c(3,"Target INR high","#2E86AB")),
  zones=list(c(0,14,2,3,"green",0.08))),
D("aptt-curve","hemato","aPTT Curve","aPTT曲線",
  "Heparin dose (U/hr)","aPTT (sec)",c(0,2000),c(20,120),
  "aPTT曲線テンプレート。ヘパリン投与量とaPTTの関係をプロット。","aPTT,ヘパリン,抗凝固",
  zones=list(c(0,2000,60,80,"green",0.08))),
D("platelet-aggregation","hemato","Platelet Aggregation","血小板凝集",
  "Time (min)","Light transmission (%)",c(0,10),c(0,100),
  "血小板凝集テンプレート。ADP/コラーゲン等の刺激剤別応答をプロット。","血小板凝集,ADP,コラーゲン",
  sub="ADP / Collagen / Epinephrine / Ristocetin"),
D("reticulocyte","hemato","Reticulocyte Count","網赤血球数",
  "Day","Reticulocyte count (%)",c(0,14),c(0,20),
  "網赤血球数の経時変化テンプレート。貧血治療効果の評価に使用。","網赤血球,貧血,治療効果"),
D("esr-curve","hemato","ESR Curve","赤沈曲線",
  "Time (min)","Sedimentation (mm)",c(0,60),c(0,100),
  "赤沈曲線テンプレート。赤血球沈降速度の経時変化をプロット。","赤沈,ESR,炎症"),
D("d-dimer","hemato","D-Dimer Levels","Dダイマー値",
  "Day","D-dimer (ug/mL FEU)",c(0,14),c(0,10),
  "Dダイマー値の経時変化テンプレート。DICやDVTのモニタリングに使用。","Dダイマー,DIC,DVT"),
D("hemolysis-markers","hemato","Hemolysis Markers","溶血マーカー",
  "Marker","Value",c(0,5),c(0,500),
  "溶血マーカーテンプレート。LDH/Haptoglobin/間接Bil等をプロット。","溶血,LDH,ハプトグロビン"),
D("dic-scoring","hemato","DIC Scoring","DICスコアリング",
  "Parameter","Score",c(0,5),c(0,4),
  "DIC診断スコアリングテンプレート。血小板/PT/FDP/フィブリノーゲンをスコア化。","DIC,スコア,診断基準"),
D("blood-type","hemato","Blood Type Template","血液型テンプレート",
  "Antiserum","Agglutination",c(0,4),c(0,2),
  "血液型判定テンプレート。抗A/抗B/抗D血清との凝集反応をプロット。","血液型,ABO,Rh"),
D("thromboelastography","hemato","Thromboelastography (TEG)","トロンボエラストグラフィー",
  "Time (min)","Amplitude (mm)",c(0,60),c(-80,80),
  "TEGテンプレート。凝固・線溶の全過程を評価。R/K/MA/Lyをプロット。","TEG,凝固,線溶,MA"),
D("coag-factor-levels","hemato","Coagulation Factor Levels","凝固因子レベル",
  "Factor","Activity (%)",c(0,10),c(0,150),
  "凝固因子活性レベルテンプレート。各因子の活性を正常値と比較。","凝固因子,活性,欠乏"),
D("peripheral-smear","hemato","Peripheral Smear Template","末梢血塗抹テンプレート",
  "Cell type","Count",c(0,6),c(0,100),
  "末梢血塗抹テンプレート。白血球分画と形態異常の記録に使用。","末梢血塗抹,白血球分画,形態"),
D("bleeding-time","hemato","Bleeding Time","出血時間",
  "Time (min)","Blood flow",c(0,15),c(0,10),
  "出血時間テンプレート。一次止血の評価に使用。","出血時間,止血,血小板"),
D("crossmatch","hemato","Crossmatch Template","交差適合試験テンプレート",
  "Phase","Result",c(0,4),c(0,3),
  "交差適合試験テンプレート。主試験・副試験の結果記録に使用。","交差適合,輸血,適合性"),

# ================================================================
# NEUROSCIENCE (22)
# ================================================================
D("eeg-normal","neuro","EEG (Normal)","脳波（正常）",
  "Time (s)","Amplitude (uV)",c(0,5),c(-100,100),
  "正常脳波テンプレート。アルファ波（8-13Hz）の正常パターンをプロット。","EEG,脳波,アルファ波"),
D("eeg-epileptic","neuro","EEG (Epileptic)","脳波（てんかん）",
  "Time (s)","Amplitude (uV)",c(0,5),c(-200,200),
  "てんかん脳波テンプレート。棘波/棘徐波複合のパターンをプロット。","EEG,てんかん,棘波"),
D("eeg-sleep","neuro","EEG (Sleep Stages)","脳波（睡眠段階）",
  "Time (hr)","Sleep stage",c(0,8),c(0,5),
  "睡眠段階の脳波テンプレート。N1-N3/REMのサイクルをプロット。","EEG,睡眠,N1,N2,N3,REM",
  yb=c(0,1,2,3,4,5), ylb=c("Wake","REM","N1","N2","N3","")),
D("ncv","neuro","Nerve Conduction Study","神経伝導検査",
  "Distance (cm)","Latency (ms)",c(0,40),c(0,10),
  "神経伝導検査テンプレート。伝導速度の測定に使用。","NCV,神経伝導,速度"),
D("emg-normal","neuro","EMG (Normal)","筋電図（正常）",
  "Time (ms)","Amplitude (mV)",c(0,100),c(-2,2),
  "正常筋電図テンプレート。MUAPの正常パターンをプロット。","EMG,筋電図,MUAP"),
D("emg-myopathic","neuro","EMG (Myopathic)","筋電図（筋原性）",
  "Time (ms)","Amplitude (mV)",c(0,100),c(-1,1),
  "筋原性筋電図テンプレート。低振幅・短持続のMUAPをプロット。","EMG,筋原性,ミオパチー"),
D("emg-neuropathic","neuro","EMG (Neuropathic)","筋電図（神経原性）",
  "Time (ms)","Amplitude (mV)",c(0,100),c(-5,5),
  "神経原性筋電図テンプレート。高振幅・長持続のMUAPをプロット。","EMG,神経原性,ニューロパチー"),
D("vep","neuro","Visual Evoked Potential","視覚誘発電位",
  "Time (ms)","Amplitude (uV)",c(0,300),c(-10,10),
  "VEPテンプレート。P100潜時の測定に使用。視神経疾患の評価。","VEP,誘発電位,P100",
  vl=list(c(100,"P100"))),
D("abr","neuro","Auditory Brainstem Response","聴性脳幹反応",
  "Time (ms)","Amplitude (uV)",c(0,10),c(-1,1),
  "ABRテンプレート。I-V波の潜時測定に使用。聴神経腫瘍の評価。","ABR,聴性脳幹反応,I-V波"),
D("ssep","neuro","Somatosensory Evoked Potential","体性感覚誘発電位",
  "Time (ms)","Amplitude (uV)",c(0,50),c(-5,5),
  "SSEPテンプレート。N20/P37等の潜時測定に使用。","SSEP,体性感覚,N20"),
D("icp-waveform","neuro","ICP Waveform","頭蓋内圧波形",
  "Time (s)","ICP (mmHg)",c(0,3),c(0,40),
  "頭蓋内圧波形テンプレート。P1/P2/P3波の形態を評価。","ICP,頭蓋内圧,波形"),
D("cerebral-autoregulation","neuro","Cerebral Autoregulation","脳血流自動調節",
  "MAP (mmHg)","CBF (mL/100g/min)",c(0,200),c(0,100),
  "脳血流自動調節テンプレート。MAPとCBFの関係をプロット。","脳血流,自動調節,MAP",
  zones=list(c(60,150,40,60,"green",0.08))),
D("pain-vas","neuro","Pain Scale (VAS)","疼痛スケール（VAS）",
  "Time point","VAS (0-10)",c(0,5),c(0,10),
  "VAS疼痛スケールテンプレート。疼痛強度の経時変化をプロット。","VAS,疼痛,評価"),
D("gcs","neuro","Glasgow Coma Scale","グラスゴー・コーマ・スケール",
  "Time","GCS score",c(0,10),c(3,15),
  "GCSテンプレート。意識レベルの経時変化をプロット。","GCS,意識,昏睡",
  hl=list(c(8,"Severe (<= 8)","#E74C3C"))),
D("nihss","neuro","NIHSS Stroke Scale","NIHSSスケール",
  "Time (hr)","NIHSS score",c(0,72),c(0,42),
  "NIHSSテンプレート。脳卒中の重症度と回復をプロット。","NIHSS,脳卒中,重症度"),
D("learning-curve","neuro","Learning/Memory Curve","学習・記憶曲線",
  "Trial number","Performance (% correct)",c(1,20),c(0,100),
  "学習・記憶曲線テンプレート。試行回数と成績の関係をプロット。","学習,記憶,試行"),
D("nerve-fiber-types","neuro","Nerve Fiber Classification","神経線維分類",
  "Fiber diameter (um)","Conduction velocity (m/s)",c(0,20),c(0,120),
  "神経線維分類テンプレート。線維径と伝導速度の関係をプロット。","神経線維,A,B,C,伝導速度"),
D("dermatome-map","neuro","Dermatome Map Template","デルマトームテンプレート",
  "Spinal level","Region",c(0,30),c(0,10),
  "デルマトーム（皮膚分節）テンプレート。脊髄レベルと支配領域の対応をプロット。","デルマトーム,皮膚分節,脊髄"),
D("pupil-reflex","neuro","Pupil Reflex","瞳孔反射",
  "Time (s)","Pupil diameter (mm)",c(0,5),c(1,8),
  "瞳孔反射テンプレート。対光反射の潜時と反応をプロット。","瞳孔,対光反射,縮瞳"),
D("nystagmus","neuro","Nystagmus Pattern","眼振パターン",
  "Time (s)","Eye position (degrees)",c(0,10),c(-30,30),
  "眼振パターンテンプレート。急速相と緩徐相の方向と振幅をプロット。","眼振,急速相,前庭"),
D("neurotransmitter","neuro","Neurotransmitter Release","神経伝達物質放出",
  "Time (ms)","Release (% of total)",c(0,20),c(0,100),
  "神経伝達物質放出テンプレート。刺激後の放出と再取り込みの時間経過をプロット。","神経伝達物質,シナプス,放出"),
D("csf-analysis","neuro","CSF Analysis Template","髄液検査テンプレート",
  "Parameter","Value",c(0,5),c(0,500),
  "髄液検査テンプレート。細胞数/蛋白/糖等の検査値をプロット。","髄液,CSF,髄膜炎"),

# ================================================================
# OB/GYN (15)
# ================================================================
D("fetal-growth","obgyn","Fetal Growth Curve","胎児発育曲線",
  "Gestational age (weeks)","Estimated weight (g)",c(10,42),c(0,4500),
  "胎児発育曲線テンプレート。在胎週数と推定体重の関係をプロット。","胎児発育,推定体重,在胎週数"),
D("fhr-normal","obgyn","FHR (Normal)","胎児心拍数（正常）",
  "Time (min)","FHR (bpm)",c(0,20),c(80,200),
  "正常胎児心拍モニタリングテンプレート。基線と基線細変動をプロット。","FHR,胎児心拍,NST",
  hl=list(c(110,"Normal baseline low"),c(160,"Normal baseline high")),
  zones=list(c(0,20,110,160,"green",0.06))),
D("fhr-variable","obgyn","FHR (Variable Decels)","胎児心拍（変動一過性徐脈）",
  "Time (min)","FHR (bpm)",c(0,20),c(60,200),
  "変動一過性徐脈の胎児心拍テンプレート。臍帯圧迫パターンをプロット。","FHR,変動一過性徐脈,臍帯"),
D("fhr-late","obgyn","FHR (Late Decels)","胎児心拍（遅発一過性徐脈）",
  "Time (min)","FHR (bpm)",c(0,20),c(80,200),
  "遅発一過性徐脈の胎児心拍テンプレート。胎盤機能不全パターンをプロット。","FHR,遅発一過性徐脈,胎盤"),
D("bishop-score","obgyn","Bishop Score","ビショップスコア",
  "Parameter","Score (0-3)",c(0,6),c(0,3),
  "ビショップスコアテンプレート。頸管成熟度の評価に使用。","ビショップ,頸管,誘発分娩"),
D("partograph","obgyn","Partograph","パルトグラフ",
  "Time (hr)","Cervical dilation (cm)",c(0,12),c(0,10),
  "パルトグラフテンプレート。分娩進行の監視に使用。","パルトグラフ,分娩進行,頸管開大"),
D("pregnancy-hormones","obgyn","Pregnancy Hormones","妊娠ホルモン",
  "Gestational age (weeks)","Hormone level",c(0,42),c(0,100),
  "妊娠中ホルモン変動テンプレート。hCG/E2/P4の推移をプロット。","妊娠ホルモン,hCG,エストロゲン",
  sub="hCG / Estradiol / Progesterone"),
D("fundal-height","obgyn","Fundal Height","子宮底長",
  "Gestational age (weeks)","Fundal height (cm)",c(16,42),c(10,40),
  "子宮底長テンプレート。在胎週数と子宮底長の関係をプロット。","子宮底長,胎児発育"),
D("afi","obgyn","Amniotic Fluid Index","羊水指数",
  "Gestational age (weeks)","AFI (cm)",c(16,42),c(0,25),
  "羊水指数テンプレート。在胎週数とAFIの正常範囲をプロット。","羊水,AFI,羊水過多",
  zones=list(c(16,42,5,25,"blue",0.05))),
D("bpp","obgyn","Biophysical Profile","バイオフィジカルプロファイル",
  "Parameter","Score (0-2)",c(0,6),c(0,2),
  "バイオフィジカルプロファイルテンプレート。胎児well-beingの評価に使用。","BPP,胎児評価,NST"),
D("friedman-curve","obgyn","Friedman Curve (Labor)","フリードマン曲線",
  "Time (hr)","Cervical dilation (cm)",c(0,14),c(0,10),
  "フリードマン曲線テンプレート。正常分娩進行のS字型パターンをプロット。","フリードマン,分娩進行,S字型"),
D("apgar","obgyn","Apgar Score","アプガースコア",
  "Time (min)","Apgar score",c(0,10),c(0,10),
  "アプガースコアテンプレート。1分/5分/10分のスコア変化をプロット。","アプガー,新生児,蘇生"),
D("gestational-growth","obgyn","Gestational Growth Chart","在胎週数別成長曲線",
  "Gestational age (weeks)","Weight (g)",c(22,42),c(0,5000),
  "在胎週数別成長曲線テンプレート。SGA/AGA/LGAの判定に使用。","成長曲線,SGA,AGA,LGA",
  sub="10th / 50th / 90th percentile"),
D("fhr-early","obgyn","FHR (Early Decels)","胎児心拍（早発一過性徐脈）",
  "Time (min)","FHR (bpm)",c(0,20),c(80,200),
  "早発一過性徐脈の胎児心拍テンプレート。児頭圧迫パターンをプロット。","FHR,早発一過性徐脈,児頭"),
D("menstrual-cycle-obgyn","obgyn","Menstrual Cycle","月経周期",
  "Day of cycle","Hormone level / Endometrial thickness",c(1,28),c(0,10),
  "月経周期テンプレート。ホルモン変動と子宮内膜変化をプロット。","月経周期,卵胞期,黄体期"),

# ================================================================
# PEDIATRICS (15)
# ================================================================
D("growth-weight-boys","peds","Growth: Weight (Boys)","成長曲線：体重（男児）",
  "Age (months)","Weight (kg)",c(0,60),c(0,25),
  "男児体重成長曲線テンプレート。パーセンタイルラインをプロット。","成長曲線,体重,男児,パーセンタイル",
  sub="3rd / 10th / 50th / 90th / 97th percentile"),
D("growth-weight-girls","peds","Growth: Weight (Girls)","成長曲線：体重（女児）",
  "Age (months)","Weight (kg)",c(0,60),c(0,25),
  "女児体重成長曲線テンプレート。パーセンタイルラインをプロット。","成長曲線,体重,女児,パーセンタイル",
  sub="3rd / 10th / 50th / 90th / 97th percentile"),
D("growth-height-boys","peds","Growth: Height (Boys)","成長曲線：身長（男児）",
  "Age (months)","Height (cm)",c(0,60),c(40,120),
  "男児身長成長曲線テンプレート。パーセンタイルラインをプロット。","成長曲線,身長,男児"),
D("growth-height-girls","peds","Growth: Height (Girls)","成長曲線：身長（女児）",
  "Age (months)","Height (cm)",c(0,60),c(40,120),
  "女児身長成長曲線テンプレート。パーセンタイルラインをプロット。","成長曲線,身長,女児"),
D("head-circumference","peds","Head Circumference","頭囲",
  "Age (months)","Head circumference (cm)",c(0,36),c(30,55),
  "頭囲成長曲線テンプレート。パーセンタイルラインをプロット。","頭囲,成長曲線"),
D("bmi-age","peds","BMI-for-Age","年齢別BMI",
  "Age (years)","BMI (kg/m2)",c(2,18),c(10,35),
  "年齢別BMI曲線テンプレート。肥満/低体重の評価に使用。","BMI,年齢,肥満,低体重"),
D("vital-signs-age","peds","Vital Signs by Age","年齢別バイタルサイン",
  "Age (years)","Value",c(0,18),c(0,200),
  "年齢別バイタルサイン基準値テンプレート。HR/RR/BPの正常範囲をプロット。","バイタルサイン,小児,基準値",
  sub="Heart rate / Respiratory rate / Blood pressure"),
D("bilirubin-nomogram","peds","Neonatal Jaundice Nomogram","新生児黄疸ノモグラム",
  "Age (hours)","Total bilirubin (mg/dL)",c(0,120),c(0,25),
  "新生児黄疸ノモグラムテンプレート。光線療法の適応判定に使用。","黄疸,ビリルビン,光線療法,新生児",
  zones=list(c(0,120,15,25,"red",0.08),c(0,120,10,15,"orange",0.06))),
D("growth-velocity","peds","Growth Velocity","成長速度",
  "Age (years)","Height velocity (cm/yr)",c(0,18),c(0,20),
  "成長速度曲線テンプレート。思春期のスパートを含む成長速度をプロット。","成長速度,思春期,スパート"),
D("weight-for-length","peds","Weight-for-Length","身長別体重",
  "Length (cm)","Weight (kg)",c(45,110),c(2,25),
  "身長別体重テンプレート。栄養状態の評価に使用。","身長別体重,栄養"),
D("milestones","peds","Developmental Milestones","発達マイルストーン",
  "Age (months)","Developmental domain",c(0,36),c(0,5),
  "発達マイルストーンテンプレート。粗大運動/微細運動/言語/社会性をプロット。","発達,マイルストーン,運動,言語"),
D("vaccine-schedule","peds","Vaccine Schedule","ワクチンスケジュール",
  "Age (months)","Vaccine",c(0,72),c(0,12),
  "定期ワクチンスケジュールテンプレート。接種時期と種類をプロット。","ワクチン,スケジュール,予防接種"),
D("fluid-calculation","peds","Fluid Calculation","小児輸液計算",
  "Body weight (kg)","Maintenance fluid (mL/hr)",c(0,40),c(0,80),
  "小児輸液計算テンプレート。体重別の維持輸液量をプロット。Holliday-Segar式。","輸液,小児,Holliday-Segar"),
D("peds-gcs","peds","Pediatric GCS","小児GCS",
  "Time","GCS score",c(0,10),c(3,15),
  "小児GCSテンプレート。小児用意識レベルスケールの経時変化をプロット。","小児GCS,意識,小児"),
D("denver-screening","peds","Denver Screening","デンバー発達スクリーニング",
  "Age (months)","Developmental area",c(0,72),c(0,5),
  "デンバー発達スクリーニングテンプレート。年齢別の発達到達度をプロット。","デンバー,発達,スクリーニング"),

# ================================================================
# ORTHOPEDICS (10)
# ================================================================
D("rom","ortho","Range of Motion","関節可動域",
  "Joint","ROM (degrees)",c(0,8),c(0,180),
  "関節可動域テンプレート。各関節の正常ROM値と測定値をプロット。","ROM,関節可動域,リハビリ"),
D("fracture-healing","ortho","Fracture Healing Timeline","骨折治癒タイムライン",
  "Weeks","Healing stage",c(0,24),c(0,5),
  "骨折治癒タイムラインテンプレート。炎症・仮骨形成・リモデリングの各段階をプロット。","骨折,治癒,仮骨"),
D("dexa","ortho","Bone Density (DEXA)","骨密度（DEXA）",
  "Age (years)","T-score",c(20,80),c(-4,2),
  "骨密度テンプレート。T-scoreと骨粗鬆症の評価に使用。","骨密度,DEXA,T-score,骨粗鬆症",
  hl=list(c(-1,"Osteopenia","#F39C12"),c(-2.5,"Osteoporosis","#E74C3C"))),
D("gait-analysis","ortho","Gait Analysis","歩行分析",
  "% Gait cycle","Joint angle (degrees)",c(0,100),c(-20,60),
  "歩行分析テンプレート。歩行周期中の関節角度変化をプロット。","歩行,分析,関節角度"),
D("muscle-strength","ortho","Muscle Strength Grading","筋力評価",
  "Muscle group","MMT grade (0-5)",c(0,8),c(0,5),
  "徒手筋力テスト（MMT）テンプレート。各筋群のグレードをプロット。","MMT,筋力,評価"),
D("cobb-angle","ortho","Scoliosis (Cobb Angle)","側弯症（コブ角）",
  "Vertebral level","Cobb angle (degrees)",c(0,20),c(0,60),
  "コブ角測定テンプレート。脊柱側弯の進行評価に使用。","コブ角,側弯症,脊柱"),
D("compartment-pressure","ortho","Compartment Pressure","コンパートメント内圧",
  "Time (hr)","Pressure (mmHg)",c(0,12),c(0,60),
  "コンパートメント内圧テンプレート。コンパートメント症候群の診断に使用。","コンパートメント,内圧,筋膜切開",
  hl=list(c(30,"Critical threshold (30mmHg)","#E74C3C"))),
D("joint-space","ortho","Joint Space Measurement","関節裂隙測定",
  "Assessment point","Joint space (mm)",c(0,5),c(0,6),
  "関節裂隙測定テンプレート。関節症の進行評価に使用。","関節裂隙,変形性関節症"),
D("bone-age","ortho","Bone Age Assessment","骨年齢評価",
  "Chronological age (years)","Bone age (years)",c(0,18),c(0,18),
  "骨年齢評価テンプレート。暦年齢との乖離をプロット。","骨年齢,成長,評価"),
D("asa-score","ortho","ASA Physical Status","ASA身体状態分類",
  "Parameter","Score",c(0,6),c(0,6),
  "ASA身体状態分類テンプレート。術前リスク評価に使用。","ASA,術前評価,リスク"),

# ================================================================
# OPHTHALMOLOGY (10)
# ================================================================
D("visual-acuity","eye","Visual Acuity","視力検査",
  "Distance (m)","logMAR",c(0,6),c(-0.3,1.5),
  "視力検査テンプレート。矯正/非矯正視力の記録に使用。","視力,logMAR,矯正"),
D("visual-field","eye","Visual Field (Perimetry)","視野検査",
  "Horizontal (degrees)","Vertical (degrees)",c(-30,30),c(-30,30),
  "視野検査テンプレート。自動視野計の結果をプロット。","視野,ペリメトリー,暗点"),
D("iop","eye","Intraocular Pressure","眼圧",
  "Time of day (hr)","IOP (mmHg)",c(6,22),c(5,30),
  "眼圧日内変動テンプレート。緑内障の評価に使用。","眼圧,IOP,緑内障",
  hl=list(c(21,"Upper normal limit","#E74C3C"))),
D("dark-adaptation","eye","Dark Adaptation","暗順応曲線",
  "Time in dark (min)","log Threshold (cd/m2)",c(0,40),c(-6,0),
  "暗順応曲線テンプレート。錐体-杆体の二段階適応をプロット。","暗順応,錐体,杆体"),
D("accommodation","eye","Accommodation Curve","調節力曲線",
  "Age (years)","Accommodation (D)",c(5,70),c(0,15),
  "調節力-年齢曲線テンプレート。加齢による調節力低下をプロット。","調節,老眼,年齢"),
D("erg","eye","Electroretinogram","網膜電図",
  "Time (ms)","Amplitude (uV)",c(0,200),c(-100,500),
  "ERGテンプレート。a波/b波の振幅と潜時を測定。","ERG,網膜電図,a波,b波"),
D("fundus","eye","Fundus Diagram","眼底図",
  "X position","Y position",c(-30,30),c(-30,30),
  "眼底図テンプレート。所見の記録とスケッチに使用。","眼底,所見,スケッチ"),
D("corneal-topography","eye","Corneal Topography","角膜トポグラフィー",
  "X (mm)","Y (mm)",c(-5,5),c(-5,5),
  "角膜トポグラフィーテンプレート。角膜形状の解析に使用。","角膜,トポグラフィー,乱視"),
D("color-vision","eye","Color Vision Test","色覚検査",
  "Test plate","Response",c(0,15),c(0,3),
  "色覚検査テンプレート。石原表等の結果記録に使用。","色覚,石原表,色覚異常"),
D("oct","eye","OCT Layer Template","OCT層構造テンプレート",
  "Position (um)","Retinal thickness (um)",c(0,6000),c(0,400),
  "OCT網膜層構造テンプレート。黄斑厚の測定に使用。","OCT,網膜,黄斑"),

# ================================================================
# PSYCHIATRY (10)
# ================================================================
D("phq9","psych","PHQ-9 Template","PHQ-9テンプレート",
  "Item","Score (0-3)",c(0,10),c(0,3),
  "PHQ-9うつ症状スクリーニングテンプレート。9項目の回答をプロット。","PHQ-9,うつ,スクリーニング"),
D("gad7","psych","GAD-7 Template","GAD-7テンプレート",
  "Item","Score (0-3)",c(0,8),c(0,3),
  "GAD-7不安症状スクリーニングテンプレート。7項目の回答をプロット。","GAD-7,不安,スクリーニング"),
D("hamd","psych","HAM-D Template","HAM-Dテンプレート",
  "Item","Score",c(0,18),c(0,4),
  "ハミルトンうつ病評価尺度テンプレート。17項目のスコアをプロット。","HAM-D,うつ病,評価"),
D("mmse","psych","MMSE Template","MMSEテンプレート",
  "Domain","Score",c(0,6),c(0,10),
  "MMSE（ミニメンタルステート検査）テンプレート。認知機能の評価に使用。","MMSE,認知機能,認知症"),
D("drug-monitoring","psych","Drug Plasma Monitoring","薬物血中濃度モニタリング",
  "Time (hr)","Plasma level (ng/mL)",c(0,24),c(0,200),
  "精神科薬物の血中濃度モニタリングテンプレート。治療域内管理に使用。","TDM,血中濃度,リチウム"),
D("mood-chart","psych","Mood Chart","気分チャート",
  "Day","Mood score (-3 to +3)",c(1,30),c(-3,3),
  "気分チャートテンプレート。双極性障害等の日々の気分変動をプロット。","気分,双極性,チャート",
  hl=list(c(0,"Euthymic"))),
D("sleep-study","psych","Sleep Study (PSG)","睡眠検査（PSG）",
  "Time (hr)","Sleep stage",c(0,8),c(0,5),
  "終夜睡眠ポリグラフテンプレート。睡眠段階の推移をプロット。","PSG,睡眠,ポリグラフ"),
D("circadian","psych","Circadian Rhythm","概日リズム",
  "Time of day (hr)","Melatonin / Core temp",c(0,24),c(0,10),
  "概日リズムテンプレート。メラトニンと深部体温の日内変動をプロット。","概日リズム,メラトニン,体温"),
D("stress-cortisol","psych","Stress Response (Cortisol)","ストレス応答（コルチゾール）",
  "Time (min)","Cortisol (ug/dL)",c(0,120),c(0,30),
  "ストレス応答テンプレート。TSST等のストレス負荷後のコルチゾール変化をプロット。","ストレス,コルチゾール,HPA軸"),
D("cognitive-assessment","psych","Cognitive Assessment","認知機能評価",
  "Domain","Score (% of max)",c(0,7),c(0,100),
  "認知機能評価テンプレート。注意/記憶/遂行機能等のドメイン別スコアをプロット。","認知機能,評価,ドメイン"),

# ================================================================
# PATHOLOGY (12)
# ================================================================
D("cell-cycle","path","Cell Cycle","細胞周期",
  "Phase","Duration (hr)",c(0,5),c(0,20),
  "細胞周期テンプレート。G1/S/G2/M期の各段階の所要時間をプロット。","細胞周期,G1,S,G2,M"),
D("tumor-growth","path","Tumor Growth (Gompertz)","腫瘍成長曲線（ゴンペルツ）",
  "Time (weeks)","Tumor volume (cm3)",c(0,30),c(0,100),
  "ゴンペルツモデルによる腫瘍成長曲線テンプレート。","腫瘍成長,ゴンペルツ,増殖"),
D("tumor-markers","path","Tumor Markers","腫瘍マーカー",
  "Time (months)","Marker level",c(0,24),c(0,100),
  "腫瘍マーカーの経時変化テンプレート。治療効果と再発のモニタリングに使用。","腫瘍マーカー,CEA,AFP,CA19-9"),
D("tnm-staging","path","TNM Staging","TNMステージング",
  "Stage","5-year survival (%)",c(0,5),c(0,100),
  "TNMステージング別生存率テンプレート。各ステージの予後をプロット。","TNM,ステージング,予後",
  xb=c(1,2,3,4), xlb=c("I","II","III","IV")),
D("wound-healing","path","Wound Healing Phases","創傷治癒段階",
  "Time (days)","Activity level",c(0,30),c(0,10),
  "創傷治癒段階テンプレート。炎症・増殖・成熟の各段階をプロット。","創傷治癒,炎症,増殖,成熟"),
D("inflammation","path","Inflammation Timeline","炎症タイムライン",
  "Time (hr)","Intensity",c(0,72),c(0,10),
  "炎症反応タイムラインテンプレート。急性炎症の時間経過をプロット。","炎症,急性,慢性"),
D("ki67","path","Ki-67 Proliferation Index","Ki-67増殖指数",
  "Sample","Ki-67 index (%)",c(0,6),c(0,100),
  "Ki-67増殖指数テンプレート。腫瘍の増殖能を評価。","Ki-67,増殖指数,腫瘍"),
D("tumor-doubling","path","Tumor Doubling Time","腫瘍倍加時間",
  "Time (months)","Tumor volume (cm3)",c(0,12),c(0,100),
  "腫瘍倍加時間テンプレート。腫瘍サイズの指数関数的増加をプロット。","倍加時間,腫瘍成長"),
D("survival-stage","path","Survival by Stage","ステージ別生存曲線",
  "Time (months)","Survival probability",c(0,60),c(0,1),
  "ステージ別生存曲線テンプレート。各ステージの生存確率を比較。","生存曲線,ステージ,予後",
  sub="Stage I / II / III / IV"),
D("recist","path","RECIST Response","RECIST治療効果判定",
  "Assessment","Sum of target lesions (mm)",c(0,6),c(0,100),
  "RECIST基準による治療効果判定テンプレート。標的病変の経時変化をプロット。","RECIST,治療効果,腫瘍縮小",
  hl=list(c(70,"PD threshold (+20%)","#E74C3C"),c(30,"PR threshold (-30%)","#2E86AB"))),
D("apoptosis","path","Apoptosis Markers","アポトーシスマーカー",
  "Time (hr)","% Apoptotic cells",c(0,48),c(0,100),
  "アポトーシスマーカーテンプレート。アポトーシス誘導後の細胞死をプロット。","アポトーシス,カスパーゼ,Annexin"),
D("metastasis","path","Metastatic Cascade","転移カスケード",
  "Stage","Efficiency (%)",c(0,6),c(0,100),
  "転移カスケードテンプレート。各段階の効率をプロット。","転移,浸潤,血行性"),

# ================================================================
# RADIOLOGY (8)
# ================================================================
D("hounsfield","radio","Hounsfield Unit Scale","ハウンスフィールド値スケール",
  "Tissue type","HU",c(0,8),c(-1000,1000),
  "ハウンスフィールド値スケールテンプレート。各組織のCT値をプロット。","HU,CT値,ハウンスフィールド"),
D("contrast-enhancement","radio","Contrast Enhancement","造影効果曲線",
  "Time (s)","Enhancement (HU)",c(0,180),c(0,200),
  "造影効果曲線テンプレート。ダイナミックCT/MRIの造影パターンをプロット。","造影,ダイナミック,TIC"),
D("dwi-adc","radio","DWI/ADC Template","DWI/ADCテンプレート",
  "b-value (s/mm2)","Signal intensity",c(0,1000),c(0,1000),
  "DWI/ADCテンプレート。拡散強調画像のb値と信号強度の関係をプロット。","DWI,ADC,拡散"),
D("suv","radio","SUV Measurement","SUV測定テンプレート",
  "Time (min)","SUV",c(0,60),c(0,20),
  "SUV測定テンプレート。PET検査のSUV値の経時変化をプロット。","SUV,PET,FDG"),
D("radiation-dose","radio","Radiation Dose Chart","放射線量チャート",
  "Examination type","Effective dose (mSv)",c(0,8),c(0,20),
  "放射線量チャートテンプレート。各検査の被曝線量を比較。","放射線量,被曝,mSv"),
D("ct-window","radio","CT Windowing","CTウィンドウ設定",
  "HU","Display brightness",c(-1000,1000),c(0,255),
  "CTウィンドウ設定テンプレート。WW/WLの概念をプロット。","CTウィンドウ,WW,WL"),
D("mri-signal","radio","MRI Signal Intensity","MRI信号強度",
  "TE (ms)","Signal intensity",c(0,200),c(0,1000),
  "MRI信号強度テンプレート。T1WI/T2WIでの組織信号をプロット。","MRI,T1,T2,信号強度"),
D("us-measurement","radio","Ultrasound Measurement","超音波計測テンプレート",
  "Parameter","Measurement (mm)",c(0,6),c(0,100),
  "超音波計測テンプレート。各臓器の計測値記録に使用。","超音波,エコー,計測"),

# ================================================================
# SURGERY/ANESTHESIA (10)
# ================================================================
D("asa-classification","surg","ASA Classification","ASA分類",
  "Class","Risk level",c(0,7),c(0,6),
  "ASA身体状態分類テンプレート。I-VI類の術前リスク評価に使用。","ASA,分類,術前評価"),
D("mallampati","surg","Mallampati Score","マランパティスコア",
  "Class","Difficulty",c(0,5),c(0,4),
  "マランパティスコアテンプレート。気管挿管困難度の予測に使用。","マランパティ,気管挿管,気道"),
D("fluid-balance","surg","Fluid Balance Chart","水分バランスチャート",
  "Time (hr)","Cumulative balance (mL)",c(0,24),c(-2000,3000),
  "水分バランスチャートテンプレート。IN/OUTバランスの経時的モニタリングに使用。","水分バランス,輸液,IN/OUT",
  hl=list(c(0,"Zero balance"))),
D("blood-gas","surg","Blood Gas Monitoring","血液ガスモニタリング",
  "Time (hr)","pH / PO2 / PCO2",c(0,24),c(0,150),
  "血液ガスモニタリングテンプレート。pH/PO2/PCO2の経時変化をプロット。","血液ガス,pH,PO2,PCO2"),
D("ventilator-wave-surg","surg","Ventilator Waveforms","人工呼吸器波形（術中）",
  "Time (s)","Pressure/Flow/Volume",c(0,6),c(-30,40),
  "術中人工呼吸器波形テンプレート。圧・流量・容量波形をプロット。","人工呼吸器,術中,波形"),
D("mac-values","surg","MAC Values","MAC値",
  "Anesthetic agent","MAC (%)",c(0,6),c(0,10),
  "MAC値テンプレート。吸入麻酔薬のMAC値比較に使用。","MAC,吸入麻酔,濃度"),
D("pain-ladder","surg","Pain Management Ladder","疼痛管理ラダー",
  "Pain severity","Treatment step",c(0,4),c(0,3),
  "WHO疼痛管理ラダーテンプレート。3段階の鎮痛法をプロット。","疼痛管理,WHO,ラダー"),
D("wound-class","surg","Surgical Wound Classification","手術創分類",
  "Class","SSI risk (%)",c(0,5),c(0,30),
  "手術創分類テンプレート。清潔/準清潔/汚染/感染の感染リスクをプロット。","手術創,SSI,感染"),
D("anesthesia-monitor","surg","Anesthesia Monitoring","麻酔モニタリング",
  "Time (min)","Value",c(0,120),c(0,200),
  "麻酔モニタリングテンプレート。HR/BP/SpO2/EtCO2の経時変化をプロット。","麻酔,モニタリング,HR,BP"),
D("surgical-checklist","surg","Surgical Checklist","手術チェックリスト",
  "Phase","Completion",c(0,4),c(0,3),
  "手術安全チェックリストテンプレート。Sign In/Time Out/Sign Outの記録に使用。","チェックリスト,安全,WHO"),

# ================================================================
# EMERGENCY MEDICINE (10)
# ================================================================
D("triage","emer","Triage Scoring","トリアージスコアリング",
  "Category","Priority",c(0,5),c(0,4),
  "トリアージスコアリングテンプレート。緊急度分類に使用。","トリアージ,緊急度,優先度"),
D("abcde","emer","ABCDE Assessment","ABCDE評価",
  "Component","Status",c(0,6),c(0,3),
  "ABCDE系統的評価テンプレート。救急初期評価の記録に使用。","ABCDE,初期評価,救急"),
D("iss","emer","Injury Severity Score","外傷重症度スコア",
  "Body region","AIS score",c(0,7),c(0,6),
  "ISS（外傷重症度スコア）テンプレート。6領域のAISスコアをプロット。","ISS,外傷,AIS,重症度"),
D("rule-of-9s","emer","Burns (Rule of 9s)","熱傷（9の法則）",
  "Body region","TBSA (%)",c(0,10),c(0,20),
  "9の法則による熱傷面積テンプレート。TBSA%の算出に使用。","熱傷,9の法則,TBSA"),
D("shock-class","emer","Shock Classification","ショック分類",
  "Class","Blood loss (mL) / HR / BP",c(0,5),c(0,2000),
  "出血性ショック分類テンプレート。I-IV度の出血量と生理学的指標をプロット。","ショック,出血,分類"),
D("resuscitation","emer","Resuscitation Timeline","蘇生タイムライン",
  "Time (min)","Intervention",c(0,30),c(0,10),
  "心肺蘇生タイムラインテンプレート。CPR/除細動/薬剤投与のタイミングをプロット。","CPR,蘇生,ACLS"),
D("toxicology","emer","Toxicology Screening","中毒スクリーニング",
  "Substance","Level",c(0,8),c(0,100),
  "中毒スクリーニングテンプレート。薬物/毒物の血中濃度を評価。","中毒,スクリーニング,血中濃度"),
D("sepsis-qsofa","emer","Sepsis (qSOFA)","敗血症（qSOFA）",
  "Time (hr)","qSOFA score / Lactate",c(0,24),c(0,6),
  "qSOFAスコアテンプレート。敗血症のスクリーニングと経過観察に使用。","qSOFA,敗血症,ラクテート"),
D("rapid-sequence","emer","Rapid Sequence Intubation","迅速導入挿管",
  "Time (min)","Step",c(0,10),c(0,8),
  "RSI（迅速導入挿管）タイムラインテンプレート。各ステップのタイミングをプロット。","RSI,挿管,迅速導入"),
D("acls","emer","ACLS Algorithm","ACLSアルゴリズム",
  "Time (min)","CPR / Shock / Drug",c(0,20),c(0,5),
  "ACLSアルゴリズムテンプレート。心停止対応のタイミングチャートをプロット。","ACLS,心停止,除細動"),

# ================================================================
# CLINICAL CHEMISTRY (10)
# ================================================================
D("calibration-curve","chem","Calibration Curve","検量線",
  "Standard concentration","Measured signal",c(0,100),c(0,100),
  "汎用検量線テンプレート。標準液濃度と測定値の直線関係をプロット。","検量線,標準,定量"),
D("linearity","chem","Linearity Assessment","直線性評価",
  "Expected value","Measured value",c(0,100),c(0,100),
  "直線性評価テンプレート。測定法の直線範囲の確認に使用。","直線性,範囲,評価"),
D("precision-profile","chem","Precision Profile","精密度プロファイル",
  "Concentration","CV (%)",c(0,100),c(0,30),
  "精密度プロファイルテンプレート。濃度別の変動係数をプロット。","精密度,CV,変動係数"),
D("method-comparison","chem","Method Comparison","方法比較",
  "Reference method","Test method",c(0,100),c(0,100),
  "方法比較テンプレート。参照法と新法の相関をプロット。","方法比較,相関,一致度"),
D("interference","chem","Interference Study","干渉試験",
  "Interferent concentration","% Recovery",c(0,100),c(80,120),
  "干渉試験テンプレート。共存物質の影響を評価。","干渉,共存物質,回収率",
  hl=list(c(100,"100% Recovery"))),
D("reference-range","chem","Reference Range","基準範囲",
  "Analyte","Value",c(0,10),c(0,100),
  "基準範囲テンプレート。各検査項目の正常値範囲をプロット。","基準範囲,正常値"),
D("qc-chart","chem","QC Chart (Levey-Jennings)","QC管理図",
  "Day","QC value",c(1,30),c(-4,4),
  "レビー・ジェニングスQC管理図テンプレート。日常の精度管理に使用。","QC,管理図,精度管理",
  hl=list(c(0,"Mean"),c(2,"+2SD","#F39C12"),c(-2,"-2SD","#F39C12"),c(3,"+3SD","#E74C3C"),c(-3,"-3SD","#E74C3C"))),
D("westgard","chem","Westgard Rules","ウエストガードルール",
  "QC run","Value (SD units)",c(0,20),c(-4,4),
  "ウエストガードルールテンプレート。QCデータの異常判定に使用。","ウエストガード,ルール,QC"),
D("analytical-sensitivity","chem","Analytical Sensitivity","分析感度",
  "Concentration","Signal",c(0,10),c(0,100),
  "分析感度テンプレート。LOD/LOQの決定に使用。","分析感度,LOD,LOQ,検出限界"),
D("clinical-limits","chem","Clinical Decision Limits","臨床判断値",
  "Analyte value","Clinical outcome probability",c(0,100),c(0,1),
  "臨床判断値テンプレート。カットオフ値の設定に使用。","臨床判断値,カットオフ,感度特異度"),

# ================================================================
# SPECIAL GRAPH TYPES (Radar, Ternary, Heatmap, Polar, etc.)
# ================================================================

# ── Radar/Spider Charts ──
D("radar-qol-6","stat","QoL Radar Chart (6-axis)","QoLレーダーチャート（6軸）",
  "","",c(0,6),c(0,1),
  "6軸のQuality of Lifeレーダーチャートテンプレート。患者の生活の質を多面的に評価。","QoL,レーダー,スパイダー,多軸",
  type="radar",xlb=c("Physical","Emotional","Social","Cognitive","Role","Global")),
D("radar-symptom-8","stat","Symptom Radar Chart (8-axis)","症状レーダーチャート（8軸）",
  "","",c(0,8),c(0,1),
  "8軸の症状評価レーダーチャート。複数症状の重症度を一覧表示。","症状,レーダー,スパイダー,評価",
  type="radar",xlb=c("Pain","Fatigue","Nausea","Dyspnea","Appetite","Sleep","Mood","Function")),
D("radar-nutrition-5","peds","Nutritional Assessment Radar","栄養評価レーダーチャート（5軸）",
  "","",c(0,5),c(0,1),
  "5軸の栄養評価レーダーチャート。小児の栄養状態を多角的に評価。","栄養,レーダー,評価,成長",
  type="radar",xlb=c("Energy","Protein","Vitamins","Minerals","Hydration")),
D("radar-motor-6","neuro","Motor Function Radar","運動機能レーダーチャート（6軸）",
  "","",c(0,6),c(0,1),
  "6軸の運動機能評価レーダーチャート。神経学的評価に使用。","運動機能,レーダー,神経,評価",
  type="radar",xlb=c("Strength","Tone","Reflexes","Coordination","Gait","Balance")),
D("radar-vitals-5","emer","Vital Signs Radar","バイタルサインレーダーチャート（5軸）",
  "","",c(0,5),c(0,1),
  "5軸のバイタルサインレーダーチャート。救急での迅速評価に使用。","バイタル,レーダー,救急,評価",
  type="radar",xlb=c("HR","BP","RR","SpO2","Temp")),

# ── Ternary Diagrams ──
D("ternary-acid-base","physiol","Acid-Base Ternary Diagram","酸塩基三角図",
  "","",c(0,1),c(0,1),
  "酸塩基平衡の三角図テンプレート。呼吸性・代謝性の酸塩基障害分類に使用。","酸塩基,三角図,pH,呼吸性,代謝性",
  type="ternary",xlb=c("Metabolic\nAcidosis","Metabolic\nAlkalosis","Respiratory")),
D("ternary-body-comp","endo","Body Composition Ternary","体組成三角図",
  "","",c(0,1),c(0,1),
  "体組成の三角図テンプレート。脂肪・筋肉・水分の割合を視覚化。","体組成,三角図,脂肪,筋肉",
  type="ternary",xlb=c("Fat Mass","Lean Mass","Water")),
D("ternary-cell-diff","hemato","Cell Differential Ternary","細胞分画三角図",
  "","",c(0,1),c(0,1),
  "血球分画の三角図テンプレート。3系統の細胞比率を可視化。","血球,分画,三角図,骨髄",
  type="ternary",xlb=c("Myeloid","Lymphoid","Erythroid")),

# ── Heatmap Templates ──
D("heatmap-antibiogram","micro","Antibiogram Heatmap","アンチバイオグラム",
  "Antibiotics","Organisms",c(0,10),c(0,8),
  "抗菌薬感受性ヒートマップ（アンチバイオグラム）。菌種×抗菌薬の感受性パターンを表示。","アンチバイオグラム,感受性,抗菌薬,ヒートマップ",
  type="heatmap",xlb=c("AMP","AMX","CEZ","CTX","IPM","VCM","GM","LVFX","MINO","SXT"),
  ylb=c("S.aureus","MRSA","E.coli","Klebsiella","Pseudomonas","Enterococcus","S.pneumo","H.influenzae")),
D("heatmap-correlation","stat","Correlation Matrix","相関行列ヒートマップ",
  "Variables","Variables",c(0,6),c(0,6),
  "相関行列ヒートマップテンプレート。変数間の相関係数を色で可視化。","相関,行列,ヒートマップ,統計",
  type="heatmap",xlb=c("Var1","Var2","Var3","Var4","Var5","Var6"),
  ylb=c("Var1","Var2","Var3","Var4","Var5","Var6")),
D("heatmap-gene-expr","path","Gene Expression Heatmap","遺伝子発現ヒートマップ",
  "Samples","Genes",c(0,8),c(0,10),
  "遺伝子発現ヒートマップテンプレート。複数サンプル間の発現パターンを比較。","遺伝子,発現,ヒートマップ,パスウェイ",
  type="heatmap"),
D("heatmap-schedule","surg","Drug Schedule Heatmap","投薬スケジュール表",
  "Days","Medications",c(0,7),c(0,6),
  "投薬スケジュールヒートマップ。術後の薬剤投与計画を可視化。","投薬,スケジュール,術後,ヒートマップ",
  type="heatmap",xlb=c("Day1","Day2","Day3","Day4","Day5","Day6","Day7"),
  ylb=c("Antibiotic","Analgesic","Anticoag","PPI","Insulin","Fluid")),

# ── Audiogram ──
D("audiogram","eye","Standard Audiogram","標準オージオグラム",
  "Frequency (Hz)","Hearing Level (dB HL)",c(125,8000),c(-10,120),
  "標準オージオグラムテンプレート。純音聴力検査結果の記録に使用。","オージオグラム,聴力,聴力検査,dB",
  type="audiogram"),

# ── Polar/Visual Field ──
D("visual-field","eye","Goldmann Visual Field","ゴールドマン視野",
  "","",c(0,30),c(0,30),
  "ゴールドマン視野検査テンプレート。視野欠損の記録と評価に使用。","視野,ゴールドマン,視野検査,眼科",
  type="polar"),
D("visual-field-humphrey","eye","Humphrey Visual Field","ハンフリー視野",
  "","",c(0,30),c(0,30),
  "ハンフリー自動視野計テンプレート。中心30度の視野感度を記録。","視野,ハンフリー,自動視野計",
  type="polar"),

# ── Special XY-based Medical Graphs ──

# Waterfall plots (Oncology)
D("waterfall-tumor","stat","Tumor Response Waterfall","腫瘍縮小率ウォーターフォール",
  "Patient","Best % Change from Baseline",c(0,30),c(-100,100),
  "腫瘍縮小率ウォーターフォールプロット。RECIST基準での治療効果を個別に表示。","ウォーターフォール,腫瘍,RECIST,治療効果",
  hl=list(c(-30,"PR threshold","#2563eb"),c(20,"PD threshold","#dc2626"))),

# Funnel plot
D("funnel-meta","stat","Funnel Plot","ファンネルプロット",
  "Effect Size","Standard Error",c(-2,2),c(0,1),
  "ファンネルプロットテンプレート。メタ分析における出版バイアスの評価に使用。","ファンネル,メタ分析,出版バイアス,対称性",
  vl=list(c(0,"","grey70")),
  zones=list(c(-1.96,1.96,0,1,"grey","0.05"))),

# QQ plot
D("qq-plot","stat","Q-Q Plot","Q-Qプロット",
  "Theoretical Quantiles","Sample Quantiles",c(-3,3),c(-3,3),
  "Q-Qプロットテンプレート。データの正規性検定に使用。","QQ,正規性,分布,統計検定"),

# Control chart (Shewhart)
D("control-chart","chem","Shewhart Control Chart","シューハート管理図",
  "Sample Number","Measured Value",c(0,30),c(-4,4),
  "シューハート管理図テンプレート。臨床検査のQC管理に使用。","管理図,QC,シューハート,精度管理",
  hl=list(c(3,"UCL (+3SD)","#dc2626"),c(2,"+2SD","#f59e0b"),c(0,"Mean","#2563eb"),c(-2,"-2SD","#f59e0b"),c(-3,"LCL (-3SD)","#dc2626"))),

# Tornado/Sensitivity chart
D("tornado-sensitivity","stat","Tornado Diagram","トルネード図",
  "Impact on Outcome","Variable",c(-50,50),c(0,10),
  "トルネード図（感度分析）テンプレート。各変数のアウトカムへの影響度を比較。","トルネード,感度分析,影響度,意思決定",
  vl=list(c(0,"Baseline","grey60"))),

# Swimmer plot
D("swimmer-treatment","stat","Swimmer Plot","スイマープロット",
  "Time (months)","Patient",c(0,36),c(0,20),
  "スイマープロットテンプレート。個々の患者の治療経過を時系列で表示。","スイマー,治療経過,タイムライン,腫瘍学"),

# Population pyramid
D("population-pyramid","epi","Population Pyramid","人口ピラミッド",
  "Population (%)","Age Group",c(-10,10),c(0,18),
  "人口ピラミッドテンプレート。年齢別・性別の人口構成を表示。","人口ピラミッド,年齢分布,人口動態,性別",
  vl=list(c(0,"","grey70")),
  ylb=c("0-4","5-9","10-14","15-19","20-24","25-29","30-34","35-39","40-44","45-49","50-54","55-59","60-64","65-69","70-74","75-79","80-84","85+"),
  yb=1:18),

# Bubble chart
D("bubble-chart","stat","Bubble Chart","バブルチャート",
  "X Variable","Y Variable",c(0,100),c(0,100),
  "バブルチャートテンプレート。3変数（X, Y, サイズ）を同時に可視化。","バブル,3変数,散布図,サイズ"),

# Dot plot (Cleveland)
D("dot-plot","stat","Cleveland Dot Plot","クリーブランドドットプロット",
  "Value","Category",c(0,100),c(0,10),
  "クリーブランドドットプロットテンプレート。カテゴリ間の比較に使用。","ドット,比較,クリーブランド,カテゴリ"),

# Lollipop chart
D("lollipop-chart","stat","Lollipop Chart","ロリポップチャート",
  "Value","Category",c(0,100),c(0,10),
  "ロリポップチャートテンプレート。棒グラフの代替として数値比較に使用。","ロリポップ,比較,カテゴリ,値"),

# Dumbbell chart (pre-post)
D("dumbbell-prepost","stat","Pre-Post Dumbbell Chart","前後比較ダンベルチャート",
  "Value","Subject",c(0,100),c(0,10),
  "ダンベルチャートテンプレート。介入前後の変化を個別に表示。","ダンベル,前後比較,介入,変化"),

# Box plot
D("box-plot-groups","stat","Box Plot (Group Comparison)","箱ひげ図（群間比較）",
  "Group","Value",c(0,6),c(0,100),
  "箱ひげ図テンプレート。複数群のデータ分布を比較。中央値・四分位・外れ値を表示。","箱ひげ図,分布,比較,中央値,四分位",
  xb=1:5,xlb=c("Control","Group A","Group B","Group C","Group D")),

# Violin plot
D("violin-plot","stat","Violin Plot","バイオリンプロット",
  "Group","Value",c(0,6),c(0,100),
  "バイオリンプロットテンプレート。データ分布の形状と密度を群間で比較。","バイオリン,分布,密度,比較",
  xb=1:5,xlb=c("Control","Group A","Group B","Group C","Group D")),

# Stacked area
D("stacked-area","epi","Stacked Area Chart","積み上げ面グラフ",
  "Time","Proportion (%)",c(0,12),c(0,100),
  "積み上げ面グラフテンプレート。時間経過に伴う構成比の変化を可視化。","積み上げ,面グラフ,構成比,時系列"),

# Step function
D("step-function","stat","Step Function Plot","ステップ関数プロット",
  "Time","Probability",c(0,10),c(0,1),
  "ステップ関数プロットテンプレート。生存曲線やイベント発生率の描画に使用。","ステップ,階段,生存,確率"),

# Bland-Altman (already exists but add difference plot variant)
D("difference-plot","stat","Difference Plot","差分プロット",
  "Mean of Methods","Difference (Method A - B)",c(0,100),c(-20,20),
  "差分プロットテンプレート。2測定法の一致度評価に使用。","差分,一致度,測定法,比較",
  hl=list(c(0,"Mean diff","#2563eb"),c(10,"+1.96SD","#dc2626"),c(-10,"-1.96SD","#dc2626"))),

# Pareto chart
D("pareto-chart","chem","Pareto Chart","パレート図",
  "Category","Frequency",c(0,10),c(0,100),
  "パレート図テンプレート。品質管理における問題の優先順位付けに使用。","パレート,品質管理,頻度,累積"),

# Gantt/timeline
D("treatment-gantt","pharm","Treatment Timeline","治療タイムライン",
  "Week","Treatment",c(0,24),c(0,8),
  "治療タイムラインテンプレート。複数薬剤の投与スケジュールを時系列で表示。","タイムライン,治療,スケジュール,投薬"),

# Nomogram (simplified as xy with scales)
D("nomogram-risk","stat","Risk Nomogram","リスクノモグラム",
  "Points","Probability",c(0,200),c(0,1),
  "リスクノモグラムテンプレート。複数因子からリスク確率を算出するためのスケール。","ノモグラム,リスク,予測,スコア"),

# Pedigree chart (simplified grid)
D("pedigree-grid","obgyn","Pedigree Chart Grid","家系図グリッド",
  "Generation Position","Generation",c(0,8),c(0,5),
  "家系図テンプレートグリッド。遺伝疾患の家族歴記録に使用。","家系図,遺伝,家族歴,系図"),

# Dermatome scoring grid
D("body-score-grid","derm","Body Area Scoring Grid","体表面積スコアグリッド",
  "Body Region","Score",c(0,10),c(0,10),
  "体表面積スコアグリッドテンプレート。皮膚疾患の範囲評価（PASI等）に使用。","体表面積,スコア,PASI,皮膚"),

# GCS trend
D("gcs-trend","neuro","GCS Trend Chart","GCS経時変化チャート",
  "Time (hours)","GCS Score",c(0,48),c(3,15),
  "GCS経時変化テンプレート。グラスゴー・コーマ・スケールの推移を記録。","GCS,意識,経時変化,神経",
  hl=list(c(8,"Severe/Moderate","#f59e0b"),c(13,"Moderate/Mild","#2563eb")),
  yb=c(3,5,7,9,11,13,15)),

# APACHE/SOFA trend
D("sofa-trend","emer","SOFA Score Trend","SOFAスコア推移",
  "ICU Day","SOFA Score",c(0,14),c(0,24),
  "SOFAスコア推移テンプレート。ICUでの臓器不全の経時的評価に使用。","SOFA,ICU,臓器不全,重症度",
  hl=list(c(6,"Moderate","#f59e0b"),c(12,"Severe","#dc2626"))),

# Pain VAS
D("vas-pain","neuro","Visual Analog Scale","VASペインスケール",
  "Time","Pain Score (VAS)",c(0,24),c(0,10),
  "VASペインスケール推移テンプレート。疼痛の経時的評価に使用。","VAS,疼痛,ペイン,評価",
  hl=list(c(3,"Mild/Moderate","#f59e0b"),c(7,"Moderate/Severe","#dc2626")),
  yb=0:10),

# Partogram
D("partogram","obgyn","Partogram","パルトグラム",
  "Time (hours)","Cervical Dilation (cm)",c(0,12),c(0,10),
  "パルトグラムテンプレート。分娩進行の記録・評価に使用。","パルトグラム,分娩,子宮口,陣痛",
  yb=0:10),

# Weight/Growth percentile
D("growth-weight","peds","Weight Growth Chart","体重成長曲線",
  "Age (months)","Weight (kg)",c(0,60),c(0,25),
  "体重成長曲線テンプレート。小児の体重推移をパーセンタイルで評価。","成長曲線,体重,パーセンタイル,小児"),
D("growth-height","peds","Height Growth Chart","身長成長曲線",
  "Age (months)","Height (cm)",c(0,60),c(40,120),
  "身長成長曲線テンプレート。小児の身長推移をパーセンタイルで評価。","成長曲線,身長,パーセンタイル,小児"),
D("growth-head","peds","Head Circumference Chart","頭囲成長曲線",
  "Age (months)","Head Circumference (cm)",c(0,36),c(30,55),
  "頭囲成長曲線テンプレート。乳幼児の頭囲推移を評価。","成長曲線,頭囲,パーセンタイル,乳幼児"),

# BMI chart
D("bmi-chart","endo","BMI Classification Chart","BMI分類チャート",
  "Height (cm)","Weight (kg)",c(140,200),c(30,140),
  "BMI分類チャートテンプレート。身長・体重からBMIゾーンを表示。","BMI,肥満,分類,体格指数",
  zones=list(c(140,200,30,55,"green","0.05"),c(140,200,55,80,"yellow","0.05"),c(140,200,80,140,"red","0.05")),
  ann=list(c(170,42,"Normal","green",3),c(170,67,"Overweight","#b8860b",3),c(170,110,"Obese","red",3)))

) # END TEMPLATES list

cat(sprintf("Defined %d templates\n", length(TEMPLATES)))
